package br.com.casanotify.tv;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.json.*;

/** Offline bundled UI, a target-origin message channel, and native certificate-pinned HTTPS. */
public final class ControlActivity extends Activity {
    private static final String ORIGIN="https://app.casanotify.local",HOME=ORIGIN+"/";
    private static final Set<String> ASSETS=new HashSet<>(Arrays.asList("/","/panel.js","/panel.css","/control.js"));
    private static final int PICK_IMAGE=42;
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private final AtomicInteger pending=new AtomicInteger();
    private SecretStore selected;private JSONObject target;private ControlClient client;private WebView web;private WebMessagePort channel;
    private int generation;private long imageRequest;private int imageGeneration;
    @Override public void onCreate(Bundle state){Ui.theme(this);super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);selected=new SecretStore(this,"control_target");try{String value=selected.read();if(!value.isEmpty())target=new JSONObject(value);}catch(Exception e){Ui.toast(this,"Não foi possível recuperar o vínculo. Selecione a TV novamente.");}if(target==null)chooseTv();else openPanel();}
    private void insets(View root){root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});}
    private void closePanel(){generation++;imageRequest=0;if(channel!=null){channel.close();channel=null;}if(web!=null){web.stopLoading();web.clearCache(true);web.destroy();web=null;}ControlClient old=client;client=null;if(old!=null)worker.execute(old::forgetSession);}
    private void chooseTv(){closePanel();LinearLayout page=Ui.page(this,"CasaNotify Controle");Ui.text(this,"",14);page.addView(Ui.text(this,"Seu celular cuida dos ajustes. Sua TV recebe os avisos.",18));page.addView(Ui.text(this,"Na TV, abra CasaNotify TV 2.2.0, autorize a sobreposição e ative o receptor. Conecte os dois aparelhos à mesma rede ou VPN.",15));EditText ip=Ui.input(this,page,"IP exibido na TV",InputType.TYPE_CLASS_PHONE);if(target!=null)ip.setText(target.optString("host"));TextView error=Ui.text(this,"",15);page.addView(error);
        Button find=Ui.button(this,page,"Conectar à minha TV",()->{});find.setOnClickListener(v->{final String host;try{host=ControlClient.ipv4(ip.getText().toString());}catch(Exception e){error.setText(e.getMessage());return;}find.setEnabled(false);error.setText("Procurando a TV…");worker.execute(()->{try{JSONObject found=ControlClient.discover(host);runOnUiThread(()->{if(isFinishing()||isDestroyed())return;find.setEnabled(true);error.setText("");confirmTv(found);});}catch(Exception e){runOnUiThread(()->{find.setEnabled(true);error.setText(e instanceof IllegalArgumentException?e.getMessage():"Não foi possível conectar. Confira o IP, a rede/VPN e se a TV está com o receptor 2.2.0 ativo.");});}});});
        if(target!=null&&!target.optString("token").isEmpty())Ui.button(this,page,"Voltar à TV salva",this::openPanel);
        Ui.button(this,page,"Termos e privacidade",()->Ui.termsDialog(this,false,null));Ui.button(this,page,"VPN deste celular",()->startActivity(new Intent(this,VpnActivity.class)));Ui.button(this,page,"Avisos dos aplicativos",this::mirror);
    }
    private void confirmTv(JSONObject found){LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(Ui.dp(this,20),Ui.dp(this,10),Ui.dp(this,20),Ui.dp(this,10));box.addView(Ui.text(this,"Na TV, abra Perfil → Identificação segura da TV. Compare todos os grupos abaixo antes de continuar. A descoberta pela rede não comprova a identidade da TV.",15));String pin=found.optString("tls_fingerprint");TextView digest=Ui.text(this,pin.replaceAll("(.{4})(?!$)","$1 "),16);digest.setTypeface(Typeface.MONOSPACE);digest.setTextIsSelectable(true);box.addView(digest);CheckBox agree=new CheckBox(this);agree.setText("Comparei: é a identificação mostrada na minha TV");box.addView(agree);EditText code=Ui.input(this,box,"Código de Vincular controle mostrado na TV",InputType.TYPE_CLASS_NUMBER);code.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(6)});ScrollView scroll=new ScrollView(this);scroll.addView(box);
        AlertDialog dialog=new AlertDialog.Builder(this).setTitle(found.optString("device_name","Minha TV")+" · "+found.optString("host")).setView(scroll).setNegativeButton("Cancelar",null).setPositiveButton("Vincular TV",null).create();dialog.setOnShowListener(d->{dialog.getButton(-1).setEnabled(false);agree.setOnCheckedChangeListener((b,on)->dialog.getButton(-1).setEnabled(on));dialog.getButton(-1).setOnClickListener(v->{String digits=code.getText().toString();if(!digits.matches("[0-9]{6}")){Ui.toast(this,"Na TV: Perfil → Vincular controle. Digite os seis números.");return;}dialog.getButton(-1).setEnabled(false);worker.execute(()->{try{String token=ControlClient.pair(found.getString("host"),LocalTls.pinned(found.getString("tls_fingerprint")),digits);found.put("token",token);selected.write(found.toString());runOnUiThread(()->{if(isDestroyed())return;target=found;dialog.dismiss();openPanel();});}catch(Exception e){runOnUiThread(()->{if(isDestroyed())return;dialog.getButton(-1).setEnabled(agree.isChecked());Ui.message(this,"Vínculo não concluído","Confira a identificação e gere um novo código em Vincular controle na TV. Atualize os dois aplicativos para 2.2.0.");});}});});});dialog.show();
    }
    private void openPanel(){closePanel();if(target==null||target.optString("token").isEmpty()){chooseTv();return;}try{client=new ControlClient(target.getString("host"),LocalTls.pinned(target.getString("tls_fingerprint")),target.getString("token"));}catch(Exception e){Ui.message(this,"Vínculo indisponível","Confira a identificação da TV e vincule novamente.");chooseTv();return;}
        final int current=generation;LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(Ui.dark(this)?0xff0c1116:0xfff1f5ef);insets(root);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(Ui.dp(this,12),0,Ui.dp(this,8),0);TextView label=Ui.text(this,"CasaNotify · "+target.optString("host"),15);bar.addView(label,new LinearLayout.LayoutParams(0,-2,1));Button menu=new Button(this);menu.setText("Menu");menu.setAllCaps(false);bar.addView(menu);menu.setOnClickListener(v->menu(menu));root.addView(bar);web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
        WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(false);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setAllowFileAccessFromFileURLs(false);settings.setAllowUniversalAccessFromFileURLs(false);settings.setBlockNetworkLoads(true);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setCacheMode(WebSettings.LOAD_NO_CACHE);settings.setJavaScriptCanOpenWindowsAutomatically(false);settings.setSupportMultipleWindows(false);settings.setSafeBrowsingEnabled(true);CookieManager.getInstance().setAcceptCookie(false);CookieManager.getInstance().setAcceptThirdPartyCookies(web,false);
        web.setWebViewClient(new WebViewClient(){
            @Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){if((ORIGIN+"/terms.txt").equals(request.getUrl().toString()))Ui.termsDialog(ControlActivity.this,false,null);else if(!HOME.equals(request.getUrl().toString())&&!request.getUrl().toString().equals(HOME+"#"))Ui.toast(ControlActivity.this,"Use o menu do aplicativo. Links externos não são abertos aqui.");return true;}
            @Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){Uri uri=request.getUrl();String path=uri.getPath();boolean local="https".equals(uri.getScheme())&&"app.casanotify.local".equals(uri.getHost())&&uri.getPort()==-1&&uri.getUserInfo()==null&&uri.getQuery()==null&&"GET".equals(request.getMethod())&&ASSETS.contains(path);if(!local)return response(403,"text/plain",new byte[0]);try(InputStream input=getAssets().open(path.equals("/")?"index.html":path.substring(1))){return response(200,path.endsWith(".js")?"application/javascript":path.endsWith(".css")?"text/css":"text/html",ControlClient.read(input,512*1024));}catch(Exception e){return response(404,"text/plain",new byte[0]);}}
            @Override public void onPageFinished(WebView view,String url){if(current!=generation||!HOME.equals(url)||channel!=null)return;WebMessagePort[] ports=view.createWebMessageChannel();channel=ports[0];channel.setWebMessageCallback(new WebMessagePort.WebMessageCallback(){@Override public void onMessage(WebMessagePort port,WebMessage message){receive(message.getData(),current);}});view.postWebMessage(new WebMessage("casanotify-native",new WebMessagePort[]{ports[1]}),Uri.parse(ORIGIN));}
        });web.loadUrl(HOME);
    }
    private static WebResourceResponse response(int status,String mime,byte[] bytes){Map<String,String> headers=new HashMap<>();headers.put("Cache-Control","no-store");headers.put("X-Content-Type-Options","nosniff");headers.put("Content-Security-Policy","default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src blob: data:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'");return new WebResourceResponse(mime,"UTF-8",status,status==200?"OK":"Blocked",headers,new ByteArrayInputStream(bytes));}
    private void menu(View anchor){PopupMenu popup=new PopupMenu(this,anchor);for(String text:new String[]{"Trocar TV","Termos e privacidade","VPN deste celular","Avisos dos aplicativos"})popup.getMenu().add(text);popup.setOnMenuItemClickListener(item->{switch(item.getTitle().toString()){case "Trocar TV":chooseTv();break;case "Termos e privacidade":Ui.termsDialog(this,false,null);break;case "VPN deste celular":startActivity(new Intent(this,VpnActivity.class));break;default:mirror();}return true;});popup.show();}
    private void mirror(){try{Class<?> activity=Class.forName("br.com.casanotify.tv.PhoneActivity");startActivity(new Intent(this,activity));}catch(ClassNotFoundException e){Ui.message(this,"Espelhamento opcional","Esta edição controla todos os ajustes da TV sem ler notificações do celular. Para enviar avisos de WhatsApp ou delivery, há a edição CasaNotify Celular no mesmo repositório. Ela exige autorização explícita do Android e pode ser restringida pelo Play Protect. Mantenha as proteções do aparelho ativadas.");}}
    private void receive(String raw,int current){long id=0;try{if(current!=generation||raw==null||raw.length()>1600000)return;JSONObject request=new JSONObject(raw);id=request.getLong("id");if(id<=0||id>9007199254740991L)return;String command=request.getString("command");if(command.equals("pickImage")){if(imageRequest!=0)throw new IllegalArgumentException("Já existe uma seleção de imagem aberta.");imageRequest=id;imageGeneration=current;Intent picker=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/png","image/jpeg","image/webp"});try{startActivityForResult(picker,PICK_IMAGE);}catch(ActivityNotFoundException e){imageRequest=0;throw new IllegalArgumentException("Nenhum seletor de imagens está disponível no Android.");}return;}
            if(command.equals("copy")){String text=request.getString("text");if(text.length()>32768)throw new IllegalArgumentException("Texto muito grande.");((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("CasaNotify",text));reply(id,new JSONObject(),null,current);return;}
            if(!command.equals("api"))throw new IllegalArgumentException("Operação não permitida.");String path=request.getString("path"),method=request.getString("method"),body=request.isNull("body")?null:request.getString("body"),csrf=request.optString("csrf");ControlClient.validate(path,method,body);if(pending.get()>=8)throw new IllegalArgumentException("Aguarde as solicitações em andamento.");ControlClient active=client;if(active==null)throw new IllegalArgumentException("Selecione a TV novamente.");final long requestId=id;pending.incrementAndGet();worker.execute(()->{try{JSONObject result=active.request(path,method,body,csrf);reply(requestId,result,null,current);}catch(javax.net.ssl.SSLException e){reply(requestId,null,"A conexão segura foi recusada. Confira a identificação e a data da TV. O certificado não foi ignorado.",current);}catch(Exception e){reply(requestId,null,"Sem resposta da TV. Confira o IP, a rede/VPN e se o receptor está ativo.",current);}finally{pending.decrementAndGet();}});
        }catch(Exception e){reply(id,null,e instanceof IllegalArgumentException?e.getMessage():"Solicitação inválida.",current);}}
    private void reply(long id,JSONObject result,String error,int current){try{String data=new JSONObject().put("id",id).put(error==null?"result":"error",error==null?result:error).toString();runOnUiThread(()->{if(current==generation&&channel!=null&&!isDestroyed())channel.postMessage(new WebMessage(data));});}catch(JSONException ignored){}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=PICK_IMAGE||imageRequest==0)return;final long id=imageRequest;final int current=imageGeneration;imageRequest=0;if(result!=RESULT_OK||data==null||data.getData()==null){reply(id,new JSONObject(),null,current);return;}Uri uri=data.getData();if(!"content".equals(uri.getScheme())){reply(id,null,"Selecione uma imagem pelo seletor do Android.",current);return;}worker.execute(()->{Bitmap bitmap=null;try{byte[] bytes;try(InputStream in=getContentResolver().openInputStream(uri)){bytes=ControlClient.read(in,8*1024*1024);}BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(options.outWidth<=0||options.outHeight<=0||(long)options.outWidth*options.outHeight>64000000)throw new IOException();options.inSampleSize=1;while(options.outWidth/options.inSampleSize>1600||options.outHeight/options.inSampleSize>1600)options.inSampleSize*=2;options.inJustDecodeBounds=false;bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(bitmap==null)throw new IOException();ByteArrayOutputStream out=new ByteArrayOutputStream();bitmap.compress(Bitmap.CompressFormat.PNG,100,out);if(out.size()>6*1024*1024)throw new IOException();reply(id,new JSONObject().put("data_url","data:image/png;base64,"+Base64.getEncoder().encodeToString(out.toByteArray())),null,current);}catch(Exception e){reply(id,null,"Escolha uma imagem PNG, JPEG ou WebP de até 8 MB e 64 megapixels.",current);}finally{if(bitmap!=null)bitmap.recycle();}});}
    @Override public void onBackPressed(){if(web!=null)new AlertDialog.Builder(this).setTitle("Fechar o controle?").setMessage("Você poderá entrar novamente com seu usuário e senha.").setPositiveButton("Fechar",(d,w)->finish()).setNegativeButton("Continuar",null).show();else super.onBackPressed();}
    @Override protected void onDestroy(){closePanel();worker.shutdown();super.onDestroy();}
}
