package br.com.casanotify.tv;
import org.junit.*;import static org.junit.Assert.*;import java.util.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;import org.json.*;

/** Deterministic attack cases confined to the test process and localhost. No external targets. */
public class AttackTest {
 private static final String TOKEN="fixture-token-only-not-a-real-secret";
 private long now=1800000000000L;private boolean revoked;
 private RequestAuth gate()throws Exception{return new RequestAuth(id->revoked?null:new RequestAuth.Key(AuthCrypto.digest(TOKEN),"control"),()->now);}
 private LanServer.Request signed(RequestAuth auth,String body)throws Exception{Map<String,String> h=new HashMap<>();for(Map.Entry<String,String> e:RequestAuth.sign("ha",TOKEN,"POST","/api/config",auth.challenge(),body,"","").entrySet())h.put(e.getKey().toLowerCase(Locale.ROOT),e.getValue());LanServer.Request r=new LanServer.Request("POST","/api/config",body,h);r.secure=true;return r;}
 @Test public void validCommandWorksOnceReplayFails()throws Exception{RequestAuth auth=gate();LanServer.Request r=signed(auth,"{\"paused\":true}");assertNotNull(auth.verify(r));assertNull(auth.verify(r));}
 @Test public void tamperedBodyMethodPathAndSessionRejected()throws Exception{for(String change:new String[]{"body","method","path","cookie","csrf"}){RequestAuth auth=gate();LanServer.Request r=signed(auth,"{}");Map<String,String> h=new HashMap<>(r.headers);if(change.equals("cookie"))h.put("cookie","stolen-session");if(change.equals("csrf"))h.put("x-casanotify-csrf","changed");LanServer.Request attack=new LanServer.Request(change.equals("method")?"GET":r.method,change.equals("path")?"/api/clear":r.path,change.equals("body")?"{\"paused\":true}":r.body,h);attack.secure=true;assertNull(change,auth.verify(attack));assertNotNull(auth.verify(r));}}
 @Test public void noKeyWrongKeyPlaintextExpiredAndRestartedProofRejected()throws Exception{RequestAuth auth=gate();LanServer.Request r=signed(auth,"{}");r.headers.put("x-casanotify-proof","0".repeat(64));assertNull(auth.verify(r));r=signed(auth,"{}");r.secure=false;assertNull(auth.verify(r));assertNull(auth.verify(new LanServer.Request("POST","/api/config","{}",new HashMap<>())));r=signed(auth,"{}");now+=60001;assertNull(auth.verify(r));r=signed(auth,"{}");assertNull(gate().verify(r));}
 @Test public void revokedClientAndChangedClientIdRejected()throws Exception{RequestAuth auth=gate();LanServer.Request r=signed(auth,"{}");r.headers.put("x-casanotify-client","a".repeat(64));assertNull(auth.verify(r));r=signed(auth,"{}");revoked=true;assertNull(auth.verify(r));}
 @Test public void challengeCacheDoesNotEvictLiveProofs()throws Exception{RequestAuth auth=gate();LanServer.Request first=signed(auth,"{}");assertNotNull(auth.verify(first));for(int i=1;i<2048;i++)assertNotNull(auth.verify(signed(auth,"{}")));assertNull(auth.verify(first));assertNull(auth.verify(signed(auth,"{}")));now+=60001;assertNotNull(auth.verify(signed(auth,"{}")));}
 @Test public void ownerSessionCannotMoveToAnotherPairedClient()throws Exception{AccountManager.Store store=new AccountManager.Store(){String value="";public String read(){return value;}public void write(String s){value=s;}public void delete(){value="";}};AccountManager accounts=new AccountManager(store);AccountManager.Session s=accounts.register("owner","Owner","long testing password",true,"phone-a");assertNotNull(accounts.session(s.id,"phone-a",false));assertNull(accounts.session(s.id,"phone-b",false));}
 @Test public void allSixteenTonesAcceptedAndArbitraryResourceRejected()throws Exception{assertEquals(16,Notice.TONES.length);for(String tone:Notice.TONES)assertEquals(tone,new Notice(new JSONObject().put("tone",tone),new JSONObject()).tone);try{new Notice(new JSONObject().put("tone","../../private"),new JSONObject());fail();}catch(IllegalArgumentException expected){}}
 @Test public void malformedUtf8AndHeaderControlsRejectedOverSocket()throws Exception{try(LanServer server=new LanServer(0,r->LanServer.Response.json(200,"{}"))){server.start();for(boolean header:new boolean[]{false,true})try(Socket socket=new Socket("127.0.0.1",server.port())){socket.setSoTimeout(5000);String head="POST /api/config HTTP/1.1\r\nHost: 127.0.0.1:"+server.port()+"\r\nContent-Type: application/json\r\nContent-Length: 2\r\n"+(header?"X-Test: a\u0001b\r\n":"")+"\r\n";socket.getOutputStream().write(head.getBytes(StandardCharsets.UTF_8));socket.getOutputStream().write(header?new byte[]{123,125}:new byte[]{(byte)0xc0,(byte)0xaf});String response=new String(socket.getInputStream().readAllBytes(),StandardCharsets.UTF_8);assertTrue(response,response.startsWith("HTTP/1.1 400"));}}}
}
