package br.com.casanotify.tv;
import org.junit.*;import static org.junit.Assert.*;import org.json.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;
public class CoreTest {
 private Notice parse(String s)throws Exception{return new Notice(new JSONObject(s),new JSONObject());}
 private void invalid(String s)throws Exception{try{parse(s);fail(s);}catch(IllegalArgumentException|JSONException expected){}}
 @Test public void defaultsAndUnicode()throws Exception{Notice n=parse("{\"message\":\"Olá!\\nEntrada \\\"principal\\\"\"}");assertEquals(10,n.duration);assertEquals("Olá!\nEntrada \"principal\"",n.json.getString("message"));assertEquals("top_right",n.position);}
 @Test public void invalidTypesAndBounds()throws Exception{for(String s:new String[]{"{\"duration\":0}","{\"duration\":121}","{\"duration\":3.5}","{\"duration\":\"10\"}","{\"opacity\":0.9}","{\"width\":900}","{\"sound\":\"yes\"}","{\"image_refresh\":1}","{\"background\":\"red\"}","{\"unknown\":true}","{\"title\":\"\",\"message\":\"\"}","{\"message\":null}"})invalid(s);}
 @Test public void explicitThemeResetsInheritedColors()throws Exception{Notice n=new Notice(new JSONObject("{\"theme\":\"ocean\",\"duration\":15}"),new JSONObject("{\"accent\":\"#A3E635\",\"width\":600,\"duration\":30}"));assertEquals("#58C6F5",n.accent);assertEquals(15,n.duration);assertEquals(600,n.width);}
 @Test public void acceptsAllPositionsAndThemes()throws Exception{for(String p:Notice.POSITIONS)assertEquals(p,parse(new JSONObject().put("position",p).toString()).position);for(String t:Notice.THEMES)assertEquals(t,parse(new JSONObject().put("theme",t).toString()).theme);}
 @Test public void imageUrlRestrictions()throws Exception{for(String s:new String[]{"file:///etc/passwd","ftp://example.com/a","javascript:alert(1)","http://user:pass@192.168.1.5/a.jpg","http://"})invalid(new JSONObject().put("image_url",s).toString());assertEquals(5,parse("{\"image_url\":\"http://192.168.1.5/a.jpg\",\"image_refresh\":5}").imageRefresh);}
 @Test public void serializationRoundTrip()throws Exception{Notice n=parse("{\"title\":\"Porta\",\"urgent\":true,\"theme\":\"paper\"}");Notice b=new Notice(n.json,new JSONObject());assertEquals(n.id,b.id);assertEquals(n.textColor,b.textColor);assertTrue(b.urgent);}
 @Test public void quietAcrossMidnight(){assertTrue(QuietHours.contains(1320,"22:00","07:00"));assertTrue(QuietHours.contains(0,"22:00","07:00"));assertTrue(QuietHours.contains(419,"22:00","07:00"));assertFalse(QuietHours.contains(420,"22:00","07:00"));assertFalse(QuietHours.contains(1300,"22:00","07:00"));}
 @Test public void quietDayAndFullDay(){assertTrue(QuietHours.contains(600,"09:00","11:00"));assertFalse(QuietHours.contains(660,"09:00","11:00"));assertTrue(QuietHours.contains(400,"00:00","00:00"));}
 @Test(expected=IllegalArgumentException.class)public void invalidClock(){QuietHours.minutes("24:00");}
 @Test public void oneTimePairing(){String c=Pairing.issue();assertTrue(c.matches("[0-9]{6}"));assertTrue(Pairing.redeem(c));assertFalse(Pairing.redeem(c));}
 @Test public void limitedPairingAttempts(){String c=Pairing.issue();for(int i=0;i<5;i++)assertFalse(Pairing.redeem("invalid"));assertFalse(Pairing.redeem(c));}
 @Test public void cancelledPairing(){String c=Pairing.issue();Pairing.cancel();assertFalse(Pairing.redeem(c));}
 private String request(String request)throws Exception{try(LanServer server=new LanServer(0,r->LanServer.Response.json(200,r.body.isEmpty()?"{}":r.body))){server.start();try(Socket s=new Socket("127.0.0.1",server.port())){s.setSoTimeout(5000);s.getOutputStream().write(request.replace("PORT",String.valueOf(server.port())).getBytes(StandardCharsets.UTF_8));s.getOutputStream().flush();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[1024];int n;while((n=s.getInputStream().read(b))!=-1)out.write(b,0,n);return out.toString("UTF-8");}}}
 @Test public void httpRoundTrip()throws Exception{String r=request("POST /api/notify HTTP/1.1\r\nHost: 127.0.0.1:PORT\r\nContent-Type: application/json\r\nContent-Length: 2\r\n\r\n{}");assertTrue(r.startsWith("HTTP/1.1 200"));assertTrue(r.endsWith("{}"));assertTrue(r.contains("Cache-Control: no-store"));assertFalse(r.contains("Access-Control-Allow-Origin"));}
 @Test public void rejectsRebindingAndCrossOrigin()throws Exception{assertTrue(request("GET / HTTP/1.1\r\nHost: evil.test:PORT\r\n\r\n").startsWith("HTTP/1.1 403"));assertTrue(request("GET / HTTP/1.1\r\nHost: 127.0.0.1:PORT\r\nOrigin: https://evil.test\r\n\r\n").startsWith("HTTP/1.1 403"));}
 @Test public void requiresJsonAndLength()throws Exception{assertTrue(request("POST /api/notify HTTP/1.1\r\nHost: 127.0.0.1:PORT\r\nContent-Length: 2\r\nContent-Type: text/plain\r\n\r\n{}").startsWith("HTTP/1.1 415"));assertTrue(request("POST /api/notify HTTP/1.1\r\nHost: 127.0.0.1:PORT\r\n\r\n").startsWith("HTTP/1.1 411"));}
 @Test public void rejectsOversizedBody()throws Exception{assertTrue(request("POST /api/notify HTTP/1.1\r\nHost: 127.0.0.1:PORT\r\nContent-Type: application/json\r\nContent-Length: 65537\r\n\r\n").startsWith("HTTP/1.1 413"));}
 @Test public void rejectsDuplicateAndChunked()throws Exception{String h="POST /api/notify HTTP/1.1\r\nHost: 127.0.0.1:PORT\r\nContent-Type: application/json\r\n";assertTrue(request(h+"Content-Length: 2\r\nContent-Length: 2\r\n\r\n{}").startsWith("HTTP/1.1 400"));assertTrue(request(h+"Transfer-Encoding: chunked\r\n\r\n").startsWith("HTTP/1.1 400"));}
 @Test public void errorResponseIsValidJson()throws Exception{String m="Campo \"errado\"\nCom tab\t e controle "+(char)1;assertEquals(m,new JSONObject(new String(LanServer.Response.error(400,m).body,StandardCharsets.UTF_8)).getString("error"));}
}
