package br.com.casanotify.tv;

import org.junit.*;
import static org.junit.Assert.*;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

public class SecurityTest {
    private static final String PASSWORD="a long testing password";
    private static class Memory implements AccountManager.Store {String value="";public String read(){return value;}public void write(String s){value=s;}public void delete(){value="";}}
    private static class Time implements AccountManager.Clock {long value=1800000000000L;public long now(){return value;}void next(){value+=30000;}}
    private interface Action {void run()throws Exception;}
    private static void rejected(Action a)throws Exception{try{a.run();fail("Expected rejection");}catch(IllegalArgumentException expected){}}
    private final Memory store=new Memory();private final Time clock=new Time();private final AccountManager accounts=new AccountManager(store,clock);private AccountManager.Session enroll()throws Exception{return accounts.register("Douglas","Douglas",PASSWORD,true);}
    @Test public void rfc6238Sha1Vectors()throws Exception{String key=AuthCrypto.base32("12345678901234567890".getBytes(StandardCharsets.US_ASCII));long[] seconds={59,1111111109L,1111111111L,1234567890L,2000000000L,20000000000L};String[] expected={"94287082","07081804","14050471","89005924","69279037","65353130"};for(int i=0;i<seconds.length;i++)assertEquals(expected[i],AuthCrypto.totp(key,seconds[i]/30,8));}
    @Test public void passwordHashAndRandomTokens()throws Exception{String salt=Base64.getEncoder().encodeToString(AuthCrypto.randomBytes(24)),hash=AuthCrypto.hash(PASSWORD,salt);assertNotEquals(PASSWORD,hash);assertTrue(AuthCrypto.same(hash,AuthCrypto.hash(PASSWORD,salt)));assertNotEquals(hash,AuthCrypto.hash("wrong password",salt));assertNotEquals(AuthCrypto.token(),AuthCrypto.token());assertEquals(43,AuthCrypto.token().length());for(int n=1;n<40;n++){byte[] b=AuthCrypto.randomBytes(n);assertArrayEquals(b,AuthCrypto.unbase32(AuthCrypto.base32(b)));}}
    @Test public void registrationRequiresConsentAndStrongPassword()throws Exception{rejected(()->accounts.register("owner","Owner",PASSWORD,false));rejected(()->accounts.register("owner","Owner","short",true));rejected(()->accounts.register("bad user","Owner",PASSWORD,true));assertFalse(accounts.exists());}
    @Test public void registrationCreatesPasswordSessionAndHidesHash()throws Exception{AccountManager.Session s=enroll();assertTrue(accounts.exists());assertEquals("douglas",accounts.profile().getString("username"));assertEquals("Douglas",accounts.profile().getString("display_name"));assertFalse(accounts.profile().getBoolean("two_factor"));assertFalse(store.value.contains("totp"));assertFalse(accounts.profile().has("password_hash"));assertFalse(store.value.contains(PASSWORD));assertSame(s,accounts.session(s.id));rejected(()->accounts.register("owner","Owner",PASSWORD,true));assertTrue(AccountManager.cookie(s).contains("Secure; HttpOnly; SameSite=Strict"));assertTrue(AccountManager.clearCookie().contains("Max-Age=0"));}
    @Test public void loginNeedsOnlyPasswordAndLogoutRevokesOneSession()throws Exception{AccountManager.Session s=enroll();AccountManager.Session next=accounts.login("DOUGLAS",PASSWORD);assertNotNull(accounts.login("douglas",PASSWORD));accounts.logout(next.id);assertNull(accounts.session(next.id));assertNotNull(accounts.session(s.id));}
    @Test public void failedLoginLockPersistsAcrossProcessRestart()throws Exception{enroll();clock.next();for(int i=0;i<5;i++)rejected(()->accounts.login("douglas","incorrect long password"));AccountManager restarted=new AccountManager(store,clock);rejected(()->restarted.login("douglas",PASSWORD));clock.value+=300001;assertNotNull(restarted.login("douglas",PASSWORD));}
    @Test public void idleAndAbsoluteSessionExpiry()throws Exception{AccountManager.Session s=enroll();clock.value+=1700000;assertNotNull(accounts.session(s.id,false));clock.value+=100001;assertNull(accounts.session(s.id));clock.next();s=accounts.login("douglas",PASSWORD);for(int i=0;i<48;i++){clock.value+=900000;assertNotNull(accounts.session(s.id));}clock.value++;assertNull(accounts.session(s.id));}
    @Test public void upgradeRemovesTotpAndPreservesOwnerPasswordConsentAndLock()throws Exception{
        enroll();JSONObject legacy=new JSONObject(store.value);String hash=legacy.getString("password_hash"),salt=legacy.getString("salt");
        legacy.put("terms_version","2026-09-26").put("totp_secret","JBSWY3DPEHPK3PXP").put("last_totp",900).put("blocked_until",clock.value+300000).put("failures",5);store.value=legacy.toString();
        AccountManager upgraded=new AccountManager(store,clock);assertTrue(upgraded.exists());JSONObject saved=new JSONObject(store.value);assertFalse(saved.has("totp_secret"));assertFalse(saved.has("last_totp"));assertEquals(hash,saved.getString("password_hash"));assertEquals(salt,saved.getString("salt"));assertEquals("2026-09-26",saved.getString("terms_version"));assertEquals("Douglas",upgraded.profile().getString("display_name"));rejected(()->upgraded.login("douglas",PASSWORD));clock.value+=300001;assertNotNull(upgraded.login("douglas",PASSWORD));assertFalse(upgraded.profile().getBoolean("two_factor"));
    }
    @Test public void passwordChangeRevokesAllSessionsAndResetRemovesOwner()throws Exception{AccountManager.Session s=enroll();clock.next();accounts.changePassword(PASSWORD,"replacement password 2026");assertNull(accounts.session(s.id));clock.next();rejected(()->accounts.login("douglas",PASSWORD));assertNotNull(accounts.login("douglas","replacement password 2026"));accounts.rename("Minha casa");assertEquals("Minha casa",accounts.profile().getString("display_name"));accounts.reset();assertFalse(accounts.exists());assertEquals("",store.value);}
    @Test public void pairingScopesAreSeparated(){String setup=Pairing.issue("setup");assertFalse(Pairing.redeem(setup,"ha"));assertTrue(Pairing.redeem(setup,"setup"));assertFalse(Pairing.redeem(setup,"setup"));String phone=Pairing.issue("phone");assertFalse(Pairing.redeem(phone,"ha"));assertTrue(Pairing.redeem(phone,"phone"));}
    @Test public void rtspValidationAndExclusiveMedia()throws Exception{String url="rtsp://user:pass@192.168.1.10:554/live";Notice n=new Notice(new JSONObject().put("video_url",url).put("tone","digital").put("backdrop","custom").put("icon","sensor"),new JSONObject());assertEquals(url,n.videoUrl);assertTrue(n.videoMuted);rejected(()->Notice.validateVideoUrl("file:///secret"));rejected(()->Notice.validateVideoUrl("rtsp://camera:70000/stream"));rejected(()->Notice.validateVideoUrl("rtsp://camera/\r\nheader"));rejected(()->new Notice(new JSONObject().put("video_url",url).put("image_url","https://example.com/image.jpg"),new JSONObject()));for(String icon:Notice.ICONS)new Notice(new JSONObject().put("icon",icon),new JSONObject());}
    @Test public void sensitivePhoneNotificationsAreFiltered(){for(String msg:new String[]{"Seu código é 123456","OTP 123456","Verification code: 123456","Nova senha","Código de entrega"})assertTrue(MirrorFilter.sensitive("App",msg));assertFalse(MirrorFilter.sensitive("Delivery","Seu pedido está chegando"));assertEquals("abc",MirrorFilter.limit("abcdef",3));}
}
