package br.com.casanotify.tv;

import org.junit.*;
import static org.junit.Assert.*;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

public class SecurityTest {
    private static final String PASSWORD="a long testing password";
    private static class Memory implements AccountManager.Store {String value="";public String read(){return value;}public void write(String s){value=s;}public void delete(){value="";}}
    private static class Time implements AccountManager.Clock {long value=1800000000000L;public long now(){return value;}void next(){value+=30000;}}
    private interface Action {void run()throws Exception;}
    private static void rejected(Action a)throws Exception{try{a.run();fail("Expected rejection");}catch(IllegalArgumentException expected){}}
    private final Memory store=new Memory();private final Time clock=new Time();private final AccountManager accounts=new AccountManager(store,clock);private String secret;
    private String code()throws Exception{return AuthCrypto.totp(secret,clock.value/30000,6);}
    private AccountManager.Session enroll()throws Exception{JSONObject r=accounts.begin("Douglas","Douglas",PASSWORD,true);secret=r.getString("secret");return accounts.confirm(r.getString("pending_id"),code());}
    @Test public void rfc6238Sha1Vectors()throws Exception{String key=AuthCrypto.base32("12345678901234567890".getBytes(StandardCharsets.US_ASCII));long[] seconds={59,1111111109L,1111111111L,1234567890L,2000000000L,20000000000L};String[] expected={"94287082","07081804","14050471","89005924","69279037","65353130"};for(int i=0;i<seconds.length;i++)assertEquals(expected[i],AuthCrypto.totp(key,seconds[i]/30,8));}
    @Test public void passwordHashAndRandomTokens()throws Exception{String salt=Base64.getEncoder().encodeToString(AuthCrypto.randomBytes(24)),hash=AuthCrypto.hash(PASSWORD,salt);assertNotEquals(PASSWORD,hash);assertTrue(AuthCrypto.same(hash,AuthCrypto.hash(PASSWORD,salt)));assertNotEquals(hash,AuthCrypto.hash("wrong password",salt));assertNotEquals(AuthCrypto.token(),AuthCrypto.token());assertEquals(43,AuthCrypto.token().length());for(int n=1;n<40;n++){byte[] b=AuthCrypto.randomBytes(n);assertArrayEquals(b,AuthCrypto.unbase32(AuthCrypto.base32(b)));}}
    @Test public void registrationRequiresConsentAndStrongPassword()throws Exception{rejected(()->accounts.begin("owner","Owner",PASSWORD,false));rejected(()->accounts.begin("owner","Owner","short",true));rejected(()->accounts.begin("bad user","Owner",PASSWORD,true));assertFalse(accounts.exists());}
    @Test public void enrollmentProvesAuthenticatorAndHidesSecrets()throws Exception{AccountManager.Session s=enroll();assertTrue(accounts.exists());assertEquals("douglas",accounts.profile().getString("username"));assertEquals("Douglas",accounts.profile().getString("display_name"));assertFalse(accounts.profile().toString().contains(secret));assertFalse(store.value.contains(PASSWORD));assertSame(s,accounts.session(s.id));rejected(()->accounts.begin("owner","Owner",PASSWORD,true));assertTrue(AccountManager.cookie(s).contains("Secure; HttpOnly; SameSite=Strict"));assertTrue(AccountManager.clearCookie().contains("Max-Age=0"));}
    @Test public void usedTotpCannotReplayAndLogoutRevokesSession()throws Exception{AccountManager.Session s=enroll();rejected(()->accounts.login("douglas",PASSWORD,code()));clock.next();AccountManager.Session next=accounts.login("DOUGLAS",PASSWORD,code());rejected(()->accounts.login("douglas",PASSWORD,code()));accounts.logout(next.id);assertNull(accounts.session(next.id));assertNotNull(accounts.session(s.id));}
    @Test public void failedLoginLockPersistsAcrossProcessRestart()throws Exception{enroll();clock.next();for(int i=0;i<5;i++)rejected(()->accounts.login("douglas","incorrect long password",code()));AccountManager restarted=new AccountManager(store,clock);rejected(()->restarted.login("douglas",PASSWORD,code()));clock.value+=300001;assertNotNull(restarted.login("douglas",PASSWORD,code()));}
    @Test public void idleAndAbsoluteSessionExpiry()throws Exception{AccountManager.Session s=enroll();clock.value+=1700000;assertNotNull(accounts.session(s.id,false));clock.value+=100001;assertNull(accounts.session(s.id));clock.next();s=accounts.login("douglas",PASSWORD,code());for(int i=0;i<48;i++){clock.value+=900000;assertNotNull(accounts.session(s.id));}clock.value++;assertNull(accounts.session(s.id));}
    @Test public void enrollmentExpiresAndLimitsAttempts()throws Exception{JSONObject p=accounts.begin("owner","Owner",PASSWORD,true);secret=p.getString("secret");String wrong=code().equals("000000")?"111111":"000000";for(int i=0;i<5;i++)rejected(()->accounts.confirm(p.getString("pending_id"),wrong));rejected(()->accounts.confirm(p.getString("pending_id"),code()));JSONObject next=accounts.begin("owner","Owner",PASSWORD,true);secret=next.getString("secret");clock.value+=600001;rejected(()->accounts.confirm(next.getString("pending_id"),code()));assertFalse(accounts.exists());}
    @Test public void passwordChangeRevokesAllSessionsAndResetRemovesOwner()throws Exception{AccountManager.Session s=enroll();clock.next();accounts.changePassword(PASSWORD,code(),"replacement password 2026");assertNull(accounts.session(s.id));clock.next();rejected(()->accounts.login("douglas",PASSWORD,code()));assertNotNull(accounts.login("douglas","replacement password 2026",code()));accounts.rename("Minha casa");assertEquals("Minha casa",accounts.profile().getString("display_name"));accounts.reset();assertFalse(accounts.exists());assertEquals("",store.value);}
    @Test public void pairingScopesAreSeparated(){String setup=Pairing.issue("setup");assertFalse(Pairing.redeem(setup,"ha"));assertTrue(Pairing.redeem(setup,"setup"));assertFalse(Pairing.redeem(setup,"setup"));String phone=Pairing.issue("phone");assertFalse(Pairing.redeem(phone,"ha"));assertTrue(Pairing.redeem(phone,"phone"));}
    @Test public void rtspValidationAndExclusiveMedia()throws Exception{String url="rtsp://user:pass@192.168.1.10:554/live";Notice n=new Notice(new JSONObject().put("video_url",url).put("tone","digital").put("backdrop","custom").put("icon","sensor"),new JSONObject());assertEquals(url,n.videoUrl);assertTrue(n.videoMuted);rejected(()->Notice.validateVideoUrl("file:///secret"));rejected(()->Notice.validateVideoUrl("rtsp://camera:70000/stream"));rejected(()->Notice.validateVideoUrl("rtsp://camera/\r\nheader"));rejected(()->new Notice(new JSONObject().put("video_url",url).put("image_url","https://example.com/image.jpg"),new JSONObject()));for(String icon:Notice.ICONS)new Notice(new JSONObject().put("icon",icon),new JSONObject());}
    @Test public void sensitivePhoneNotificationsAreFiltered(){for(String msg:new String[]{"Seu código é 123456","OTP 123456","Verification code: 123456","Nova senha","Código de entrega"})assertTrue(MirrorFilter.sensitive("App",msg));assertFalse(MirrorFilter.sensitive("Delivery","Seu pedido está chegando"));assertEquals("abc",MirrorFilter.limit("abcdef",3));}
}
