package br.com.casanotify.tv;
import android.app.*;import android.content.*;import android.content.pm.*;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;

public final class PhoneActivity extends Activity {
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private SharedPreferences settings;private LinearLayout apps;private TextView state;private JSONObject target;private Switch enabled;
    public void onCreate(Bundle b){Ui.theme(this);super.onCreate(b);settings=getSharedPreferences("phone",MODE_PRIVATE);LinearLayout p=Ui.page(this,"CasaNotify Celular");p.addView(Ui.text(this,"Esta edição envia à sua TV notificações dos aplicativos que você escolher. Ela não inicia o receptor da TV. O envio é opcional, exige autorização do Android e pode ser desligado a qualquer momento. Outras pessoas próximas à TV podem ver os avisos.",16));state=Ui.text(this,"",15);p.addView(state);
        EditText host=Ui.input(this,p,"IP da TV",InputType.TYPE_CLASS_TEXT);try{String saved=new SecretStore(this,"phone_target").read();if(!saved.isEmpty()){target=new JSONObject(saved);host.setText(target.optString("host"));}}catch(Exception e){Ui.toast(this,"Vincule a TV novamente.");}
        Ui.button(this,p,"Encontrar TV e conferir certificado",()->{String address=host.getText().toString();state.setText("Procurando TV…");worker.execute(()->{try{JSONObject info=PhoneApi.discover(address);onUi(()->approve(info));}catch(Exception e){onUi(()->Ui.message(this,"Conexão","Não foi possível acessar a TV. Confira o IP, a rede e o receptor CasaNotify TV 2.0.2 ativo."));}});});
        Ui.button(this,p,"Autorizar acesso às notificações",this::requestListenerAccess);
        enabled=new Switch(this);enabled.setText("Enviar notificações dos apps selecionados");enabled.setChecked(settings.getBoolean("enabled",false));enabled.setOnCheckedChangeListener((v,on)->{if(on&&(target==null||!Ui.accepted(this)||!permitted())){enabled.setChecked(false);Ui.message(this,"Antes de ativar","Vincule a TV, aceite os termos e autorize o acesso a notificações no Android antes de ativar o envio. Se o Android bloquear essa permissão, o espelhamento ficará indisponível.");return;}settings.edit().putBoolean("enabled",on).apply();});p.addView(enabled);
        Switch content=new Switch(this);content.setText("Incluir título e conteúdo das mensagens");content.setChecked(settings.getBoolean("content",false));content.setOnCheckedChangeListener((v,on)->settings.edit().putBoolean("content",on).apply());p.addView(content);p.addView(Ui.text(this,"Com conteúdo desligado, a TV mostra apenas o nome do aplicativo. Outras pessoas próximas à TV podem ler as mensagens. Códigos e notificações sensíveis são filtrados quando identificados.",14));
        Ui.button(this,p,"Enviar teste do celular",()->worker.execute(()->{try{if(target==null)throw new Exception();PhoneApi.call(target,"/api/notify",new JSONObject().put("id","phone-test").put("title","Celular conectado!").put("message","Obrigado por conectar seu celular ao CasaNotify TV."));onUi(()->Ui.toast(this,"Teste enviado."));}catch(Exception e){onUi(()->Ui.toast(this,"Não foi possível enviar o teste. Confira o vínculo e a rede."));}}));
        Ui.button(this,p,"Desvincular este celular",()->{new SecretStore(this,"phone_target").delete();target=null;settings.edit().putBoolean("enabled",false).apply();enabled.setChecked(false);Ui.toast(this,"Vínculo local removido. Você pode revogar a credencial também no painel da TV.");});
        Ui.button(this,p,"Tema do aplicativo",this::themeDialog);Ui.button(this,p,"VPN e rede privada",()->startActivity(new Intent(this,VpnActivity.class)));Ui.button(this,p,"Entender os bloqueios do Android",()->Ui.message(this,"Proteção do Android","O acesso às notificações é sensível e pode ser bloqueado em apps instalados por arquivo APK. Mantenha o Play Protect ativo. Se o Android negar o acesso, não há envio automático de notificações; os avisos do Home Assistant na TV continuam independentes deste recurso."));p.addView(Ui.text(this,"Aplicativos autorizados",21));apps=new LinearLayout(this);apps.setOrientation(LinearLayout.VERTICAL);p.addView(apps);loadApps();Ui.button(this,p,"Termos e privacidade",()->Ui.termsDialog(this,!Ui.accepted(this),null));Ui.button(this,p,"Fechar",this::finish);if(!Ui.accepted(this))p.post(()->Ui.termsDialog(this,true,()->Ui.message(this,"Bem-vindo!","Obrigado por conectar seu celular. Vincule a TV, escolha os aplicativos e autorize o acesso no Android somente se quiser ativar o espelhamento.")));
    }
    private void onUi(Runnable action){runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())action.run();});}
    private void approve(JSONObject info){if(isFinishing())return;new AlertDialog.Builder(this).setTitle("Confira na sua TV").setMessage("TV: "+info.optString("device_name")+"\n\nAbra ‘Segurança do painel’ na TV e compare toda a impressão digital:\n\n"+info.optString("tls_fingerprint")+"\n\nContinue somente se forem iguais.").setPositiveButton("Certificado igual",(d,w)->pair(info)).setNegativeButton("Cancelar",null).show();}
    private void pair(JSONObject info){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);int pad=Ui.dp(this,20);p.setPadding(pad,pad,pad,pad);p.addView(Ui.text(this,"Na TV, abra ‘Vincular celular para avisos’ e informe o código de seis números.",16));EditText code=Ui.input(this,p,"Código da TV",InputType.TYPE_CLASS_NUMBER);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Vincular celular").setView(p).setPositiveButton("Vincular",null).setNegativeButton("Cancelar",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{String value=code.getText().toString().trim();if(!value.matches("[0-9]{6}")){code.setError("Digite seis números");return;}dialog.getButton(-1).setEnabled(false);worker.execute(()->{try{JSONObject response=PhoneApi.call(info,"/api/pair",new JSONObject().put("code",value).put("client","phone").put("name",Build.MODEL));info.put("token",response.getString("token"));new SecretStore(this,"phone_target").write(info.toString());target=info;onUi(()->{dialog.dismiss();Ui.message(this,"Obrigado!","Seu celular foi vinculado. Escolha os aplicativos e ative o envio quando desejar.");refresh();});}catch(Exception e){onUi(()->{dialog.getButton(-1).setEnabled(true);code.setError("Confira o código, a data da TV e o certificado.");});}});}));dialog.show();}
    private void loadApps(){worker.execute(()->{List<ResolveInfo> list=getPackageManager().queryIntentActivities(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER),0);list.sort(Comparator.comparing(a->a.loadLabel(getPackageManager()).toString().toLowerCase(Locale.ROOT)));onUi(()->{if(isFinishing())return;Set<String> seen=new HashSet<>();for(ResolveInfo item:list){String pkg=item.activityInfo.packageName;if(pkg.equals(getPackageName())||!seen.add(pkg))continue;CheckBox check=new CheckBox(this);check.setText(item.loadLabel(getPackageManager()));check.setChecked(settings.getStringSet("apps",Collections.emptySet()).contains(pkg));check.setOnCheckedChangeListener((v,on)->{Set<String> selected=new HashSet<>(settings.getStringSet("apps",Collections.emptySet()));if(on)selected.add(pkg);else selected.remove(pkg);settings.edit().putStringSet("apps",selected).apply();});apps.addView(check);}if(seen.isEmpty())apps.addView(Ui.text(this,"Nenhum aplicativo visível. Use este recurso no celular.",16));});});}
    protected void onResume(){super.onResume();refresh();}
    private void refresh(){if(state!=null){boolean allowed=permitted();if(!allowed&&enabled!=null)enabled.setChecked(false);state.setText((target==null?"TV não vinculada":"TV vinculada")+" · "+(allowed?"Acesso autorizado":"Sem acesso às notificações — envio automático indisponível")+"\n"+settings.getString("last_status","Nenhum envio realizado"));}}
    private boolean permitted(){String listeners=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");return listeners!=null&&Arrays.asList(listeners.split(":")).contains(new ComponentName(this,PhoneNotificationService.class).flattenToString());}
    private void requestListenerAccess(){if(!Ui.accepted(this)){Ui.termsDialog(this,true,this::requestListenerAccess);return;}new AlertDialog.Builder(this).setTitle("Acesso às notificações").setMessage("O Android permite que um aplicativo autorizado leia notificações de outros apps, incluindo possíveis dados pessoais. O CasaNotify encaminha apenas os aplicativos selecionados à TV vinculada, por HTTPS; o conteúdo fica desativado por padrão. Você pode revogar a permissão nas configurações do Android. Se houver bloqueio do sistema, mantenha a proteção ativa e deixe o envio desligado.").setPositiveButton("Abrir configurações",(d,w)->{try{startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS));}catch(Exception e){Ui.message(this,"Permissão","Não foi possível abrir o acesso a notificações neste aparelho.");}}).setNegativeButton("Agora não",null).show();}
    private void themeDialog(){String[] ids={"system","light","dark"};String current=new Prefs(this).config().optString("ui_theme","system");new AlertDialog.Builder(this).setTitle("Tema do aplicativo").setSingleChoiceItems(new String[]{"Seguir o sistema","Claro","Escuro"},Arrays.asList(ids).indexOf(current),(d,w)->{try{new Prefs(this).update(new JSONObject().put("ui_theme",ids[w]));d.dismiss();recreate();}catch(Exception e){Ui.toast(this,"Não foi possível salvar o tema.");}}).setNegativeButton("Cancelar",null).show();}
    protected void onDestroy(){worker.shutdownNow();super.onDestroy();}
}
