package br.com.casanotify.tv;
import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;
public final class LanServer implements AutoCloseable {
 public interface Handler{Response handle(Request r)throws Exception;}
 public static final class Request{public final String method,path,body;public boolean secure;public final Map<String,String> headers;Request(String m,String p,String b,Map<String,String> h){method=m;path=p;body=b;headers=h;}}
 public static final class Response{public final int status;public final String type;public final byte[] body;public final Map<String,String> extraHeaders=new LinkedHashMap<>();public Response header(String k,String v){if(k.matches("[A-Za-z-]+")&&v.indexOf(13)<0&&v.indexOf(10)<0)extraHeaders.put(k,v);return this;}public Response(int s,String t,byte[] b){status=s;type=t;body=b;}public static Response json(int s,String b){return new Response(s,"application/json; charset=utf-8",b.getBytes(StandardCharsets.UTF_8));}public static Response error(int s,String e){return json(s,"{\"error\":"+org.json.JSONObject.quote(e)+"}");}}
 private final ServerSocket server;private final Handler handler;private final ThreadPoolExecutor pool;private final Set<Socket> clients=ConcurrentHashMap.newKeySet();private volatile boolean closed;private final boolean secure;private final long inputTimeout,outputTimeout;
 public LanServer(int port,Handler h)throws IOException{this(port,h,null);}
 public LanServer(int port,Handler h,javax.net.ssl.SSLContext tls)throws IOException{this(port,h,tls,10000,8000);}
 LanServer(int port,Handler h,javax.net.ssl.SSLContext tls,long inputMillis,long outputMillis)throws IOException{inputTimeout=inputMillis;outputTimeout=outputMillis;handler=h;secure=tls!=null;server=tls==null?new ServerSocket():tls.getServerSocketFactory().createServerSocket();if(server instanceof javax.net.ssl.SSLServerSocket){javax.net.ssl.SSLServerSocket ssl=(javax.net.ssl.SSLServerSocket)server;java.util.List<String> protocols=new ArrayList<>();for(String protocol:ssl.getSupportedProtocols())if(protocol.equals("TLSv1.2")||protocol.equals("TLSv1.3"))protocols.add(protocol);ssl.setEnabledProtocols(protocols.toArray(new String[0]));}server.setReuseAddress(true);server.bind(new InetSocketAddress(port),16);pool=new ThreadPoolExecutor(4,4,0,TimeUnit.SECONDS,new ArrayBlockingQueue<>(8),r->{Thread t=new Thread(r,"CasaNotify-http");t.setDaemon(true);return t;});}
 public int port(){return server.getLocalPort();}
 private boolean admit(Socket socket){synchronized(clients){int from=0;for(Socket client:clients)if(client.getInetAddress().equals(socket.getInetAddress()))from++;if(closed||clients.size()>=12||from>=2)return false;clients.add(socket);return true;}}
 private void release(Socket socket){synchronized(clients){clients.remove(socket);}}
 private static void abort(Socket socket){try{socket.setSoLinger(true,0);}catch(IOException ignored){}try{socket.close();}catch(IOException ignored){}}
 public void start(){Thread t=new Thread(()->{while(!closed)try{Socket s=server.accept();s.setSoTimeout(5000);if(!admit(s)){abort(s);continue;}NetworkDeadline limit=new NetworkDeadline(inputTimeout,()->abort(s));try{pool.execute(()->serve(s,limit));}catch(RejectedExecutionException e){limit.close();abort(s);release(s);}}catch(IOException e){if(!closed)close();}},"CasaNotify-listener");t.setDaemon(true);t.start();}
 private void serve(Socket s,NetworkDeadline limit){try(Socket socket=s){Response r;try{if(socket instanceof javax.net.ssl.SSLSocket)((javax.net.ssl.SSLSocket)socket).startHandshake();Request request=parse(socket);request.secure=secure;limit.close();limit=new NetworkDeadline(65000,()->abort(socket));r=handler.handle(request);}catch(HttpError e){r=Response.error(e.status,e.getMessage());}catch(SocketTimeoutException e){r=Response.error(408,"Tempo esgotado.");}catch(Exception e){r=Response.error(500,"Não foi possível processar a solicitação.");}limit.close();limit=new NetworkDeadline(outputTimeout,()->abort(socket));OutputStream out=socket.getOutputStream();StringBuilder extra=new StringBuilder();for(Map.Entry<String,String> entry:r.extraHeaders.entrySet())extra.append(entry.getKey()).append(": ").append(entry.getValue()).append("\r\n");String head="HTTP/1.1 "+r.status+" "+(r.status<300?"OK":"Error")+"\r\nContent-Type: "+r.type+"\r\nContent-Length: "+r.body.length+"\r\n"+extra+"Connection: close\r\nCache-Control: no-store\r\nX-Content-Type-Options: nosniff\r\nReferrer-Policy: no-referrer\r\nX-Frame-Options: DENY\r\nContent-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'\r\n\r\n";out.write(head.getBytes(StandardCharsets.US_ASCII));out.write(r.body);out.flush();}catch(IOException ignored){}finally{limit.close();release(s);}}
 private Request parse(Socket s)throws Exception{InputStream in=new BufferedInputStream(s.getInputStream());ByteArrayOutputStream h=new ByteArrayOutputStream();int state=0;long deadline=System.nanoTime()+8_000_000_000L;while(state<4){if(System.nanoTime()>deadline)throw new HttpError(408,"Tempo esgotado.");int b=in.read();if(b<0)throw new HttpError(400,"Cabeçalho incompleto.");h.write(b);if(h.size()>16384)throw new HttpError(431,"Cabeçalho muito grande.");int expected=state==0||state==2?13:10;state=b==expected?state+1:(b==13?1:0);}
  String[] lines=new String(h.toByteArray(),StandardCharsets.ISO_8859_1).split("\r\n"),first=lines[0].split(" ",-1);if(first.length!=3||!first[0].matches("[A-Z]+")||(!first[1].startsWith("/")||first[1].chars().anyMatch(c->c<=32||c==127))||first[1].length()>2048||!first[2].equals("HTTP/1.1"))throw new HttpError(400,"HTTP inválido.");if(!first[0].equals("GET")&&!first[0].equals("POST"))throw new HttpError(405,"Método não permitido.");if(lines.length>65)throw new HttpError(431,"Muitos cabeçalhos.");Map<String,String> headers=new HashMap<>();for(int i=1;i<lines.length;i++){int c=lines[i].indexOf(':');if(c<=0)throw new HttpError(400,"Cabeçalho inválido.");String k=lines[i].substring(0,c).toLowerCase(Locale.ROOT),v=lines[i].substring(c+1);if(!k.matches("[a-z0-9!#$%&'*+.^_`|~-]+")||headers.containsKey(k)||v.chars().anyMatch(ch->ch<32&&ch!=9||ch==127))throw new HttpError(400,"Cabeçalho duplicado ou inválido.");headers.put(k,v.trim());}
  String host=headers.get("host");if(host==null)throw new HttpError(400,"Host obrigatório.");URI u;try{u=new URI("http://"+host);}catch(Exception e){throw new HttpError(400,"Host inválido.");}String hostname=u.getHost();if(hostname==null||u.getRawUserInfo()!=null||!u.getPath().isEmpty()||u.getQuery()!=null||u.getFragment()!=null||u.getPort()!=port())throw new HttpError(403,"Use o IP e a porta exibidos na TV.");hostname=hostname.replace("[","").replace("]","");if(!hostname.equalsIgnoreCase(s.getLocalAddress().getHostAddress())&&!(s.getLocalAddress().isLoopbackAddress()&&Arrays.asList("localhost","127.0.0.1","::1").contains(hostname)))throw new HttpError(403,"Use o IP da TV.");String origin=headers.get("origin");if(origin!=null&&!origin.equalsIgnoreCase((secure?"https://":"http://")+host))throw new HttpError(403,"Origem não autorizada.");if(headers.containsKey("transfer-encoding"))throw new HttpError(400,"Use Content-Length.");String raw=headers.get("content-length");int length=0;if(raw!=null){if(!raw.matches("[0-9]{1,8}"))throw new HttpError(400,"Tamanho inválido.");length=Integer.parseInt(raw);}if(length>(first[1].equals("/api/media")?1600000:65536))throw new HttpError(413,"Arquivo ou solicitação muito grande.");if(first[0].equals("POST")){if(raw==null)throw new HttpError(411,"Content-Length obrigatório.");if(!headers.getOrDefault("content-type","").split(";",2)[0].trim().equalsIgnoreCase("application/json"))throw new HttpError(415,"Use application/json.");}if(first[0].equals("GET")&&length!=0)throw new HttpError(400,"GET não aceita corpo.");if(headers.containsKey("content-encoding")&&!headers.get("content-encoding").equalsIgnoreCase("identity"))throw new HttpError(415,"Corpo comprimido não aceito.");byte[] data=new byte[length];int read=0;while(read<length){if(System.nanoTime()>deadline)throw new HttpError(408,"Tempo esgotado.");int n=in.read(data,read,length-read);if(n<0)throw new HttpError(400,"Corpo incompleto.");read+=n;}String body=decode(data);if(first[0].equals("POST"))try{BoundedJson.checkObject(body,1600000);}catch(IllegalArgumentException e){throw new HttpError(400,"JSON inválido ou excede limites.");}return new Request(first[0],first[1],body,Collections.unmodifiableMap(headers));
 }
 private static String decode(byte[] data)throws HttpError{try{return StandardCharsets.UTF_8.newDecoder().onMalformedInput(java.nio.charset.CodingErrorAction.REPORT).onUnmappableCharacter(java.nio.charset.CodingErrorAction.REPORT).decode(java.nio.ByteBuffer.wrap(data)).toString();}catch(java.nio.charset.CharacterCodingException e){throw new HttpError(400,"UTF-8 inválido.");}}
 public void close(){closed=true;try{server.close();}catch(IOException ignored){}for(Socket s:clients)try{s.close();}catch(IOException ignored){}pool.shutdownNow();}
 private static final class HttpError extends Exception{final int status;HttpError(int s,String m){super(m);status=s;}}
}
