package br.com.casanotify.tv;
import android.content.Context;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;
public final class NoticeView extends LinearLayout {
 public final ImageView image;public final TextureView video;public final TextView mediaStatus;public final ProgressBar progress;
 public NoticeView(Context c,Notice n){super(c);setOrientation(VERTICAL);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.parseColor(n.background));bg.setCornerRadius(dp(n.radius));bg.setStroke(dp(1),alpha(Color.parseColor(n.accent),65));setBackground(bg);if(n.backdrop.equals("custom")){Bitmap wall=new MediaAssets(c).bitmap("background");if(wall!=null){android.graphics.drawable.BitmapDrawable photo=new android.graphics.drawable.BitmapDrawable(getResources(),wall);photo.setGravity(Gravity.FILL);android.graphics.drawable.GradientDrawable shade=new android.graphics.drawable.GradientDrawable();shade.setColor(alpha(Color.parseColor(n.background),210));android.graphics.drawable.LayerDrawable layers=new android.graphics.drawable.LayerDrawable(new android.graphics.drawable.Drawable[]{photo,shade});setBackground(layers);}}setClipToOutline(true);
  int space=(int)(getResources().getDisplayMetrics().heightPixels/getResources().getDisplayMetrics().density)-2*n.margin-52;int imageHeight=n.imageUrl.isEmpty()&&n.videoUrl.isEmpty()?0:Math.min(176,Math.max(64,space/3));int lines=Math.max(1,Math.min(8,(space-imageHeight-2*(n.textSize+7))/(n.textSize+6)));
  LinearLayout body=new LinearLayout(c);body.setPadding(dp(18),dp(16),dp(18),dp(16));body.setGravity(Gravity.TOP);addView(body);
  IconView icon=new IconView(c,n.icon,Color.parseColor(n.accent));LayoutParams ip=new LayoutParams(dp(38),dp(38));ip.rightMargin=dp(12);body.addView(icon,ip);
  LinearLayout words=new LinearLayout(c);words.setOrientation(VERTICAL);body.addView(words,new LayoutParams(0,-2,1));TextView title=new TextView(c);title.setText(n.title);title.setTextSize(n.textSize+3);title.setTextColor(Color.parseColor(n.textColor));title.setTypeface(Typeface.create("sans-serif-medium",0));title.setMaxLines(2);title.setEllipsize(android.text.TextUtils.TruncateAt.END);words.addView(title);
  if(!n.message.isEmpty()){TextView text=new TextView(c);text.setText(n.message);text.setTextSize(n.textSize);text.setTextColor(alpha(Color.parseColor(n.textColor),225));text.setPadding(0,dp(5),0,0);text.setMaxLines(lines);text.setEllipsize(android.text.TextUtils.TruncateAt.END);words.addView(text);}
  image=new ImageView(c);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setVisibility(GONE);LayoutParams im=new LayoutParams(-1,dp(imageHeight));im.setMargins(dp(14),0,dp(14),dp(12));addView(image,im);
  video=new TextureView(c);video.setOpaque(false);video.setVisibility(n.videoUrl.isEmpty()?GONE:VISIBLE);LayoutParams vp=new LayoutParams(-1,dp(imageHeight));vp.setMargins(dp(14),0,dp(14),dp(12));addView(video,vp);
  mediaStatus=new TextView(c);mediaStatus.setTextSize(12);mediaStatus.setTextColor(alpha(Color.parseColor(n.textColor),200));mediaStatus.setPadding(dp(20),0,dp(20),dp(10));mediaStatus.setVisibility(GONE);addView(mediaStatus);
  progress=new ProgressBar(c,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(1000);progress.setProgress(1000);progress.setProgressTintList(android.content.res.ColorStateList.valueOf(Color.parseColor(n.accent)));progress.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.TRANSPARENT));addView(progress,new LayoutParams(-1,dp(3)));progress.setVisibility(n.progress?VISIBLE:GONE);
 }
 private int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}private static int alpha(int c,int a){return(c&0xffffff)|(a<<24);}
 public static final class IconView extends View{
  private final Paint p=new Paint(3);private final Path path=new Path();private final String name;private final int color;
  public IconView(Context c,String n,int color){super(c);name=n;this.color=color;setContentDescription(n);}
  protected void onDraw(Canvas c){super.onDraw(c);c.save();c.scale(getWidth()/40f,getHeight()/40f);p.setStyle(Paint.Style.FILL);p.setColor(alpha(color,28));c.drawRoundRect(0,0,40,40,11,11,p);p.setColor(color);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setStrokeCap(Paint.Cap.ROUND);p.setStrokeJoin(Paint.Join.ROUND);path.reset();
   switch(name){case "sensor":c.drawCircle(20,20,4,p);c.drawArc(8,8,32,32,-55,110,false,p);c.drawArc(8,8,32,32,125,110,false,p);break;case "motion":c.drawCircle(22,10,3,p);c.drawLine(21,15,17,24,p);c.drawLine(18,20,28,22,p);c.drawLine(18,24,11,30,p);c.drawLine(18,24,24,32,p);c.drawLine(18,16,11,18,p);break;case "temperature":c.drawRoundRect(17,8,23,27,3,3,p);c.drawCircle(20,29,5,p);c.drawLine(20,15,20,28,p);break;case "humidity":case "water":path.moveTo(20,8);path.cubicTo(7,24,9,32,20,32);path.cubicTo(31,32,33,24,20,8);c.drawPath(path,p);break;case "phone":c.drawRoundRect(12,7,28,33,3,3,p);c.drawLine(17,29,23,29,p);break;case "delivery":c.drawRect(8,14,25,28,p);c.drawRect(25,19,32,28,p);c.drawCircle(13,30,3,p);c.drawCircle(28,30,3,p);break;case "chat":c.drawRoundRect(8,10,32,28,5,5,p);c.drawLine(14,28,11,33,p);c.drawLine(11,33,22,28,p);c.drawLine(14,17,26,17,p);c.drawLine(14,22,23,22,p);break;case "battery":c.drawRoundRect(8,13,30,28,3,3,p);c.drawLine(33,18,33,23,p);c.drawLine(13,17,13,24,p);c.drawLine(18,17,18,24,p);c.drawLine(23,17,23,24,p);break;case "wifi":c.drawArc(7,10,33,36,220,100,false,p);c.drawArc(12,16,28,32,220,100,false,p);c.drawCircle(20,29,2,p);break;case "lock":c.drawRoundRect(11,18,29,32,3,3,p);c.drawArc(15,8,25,25,180,180,false,p);c.drawPoint(20,25,p);break;case "smoke":case "alarm":c.drawCircle(20,24,8,p);c.drawLine(20,20,20,25,p);c.drawPoint(20,28,p);c.drawLine(9,10,13,14,p);c.drawLine(20,6,20,12,p);c.drawLine(31,10,27,14,p);break;case "home":path.moveTo(10,19);path.lineTo(20,10);path.lineTo(30,19);path.moveTo(13,17);path.lineTo(13,30);path.lineTo(18,30);path.lineTo(18,23);path.lineTo(23,23);path.lineTo(23,30);path.lineTo(28,30);path.lineTo(28,17);c.drawPath(path,p);break;case "door":c.drawRect(13,10,28,31,p);c.drawLine(9,31,31,31,p);c.drawCircle(23,21,1,p);break;case "camera":c.drawRoundRect(9,14,31,29,3,3,p);c.drawCircle(20,21,4,p);c.drawLine(16,10,24,10,p);break;case "check":path.moveTo(11,21);path.lineTo(17,27);path.lineTo(30,13);c.drawPath(path,p);break;case "warning":path.moveTo(20,10);path.lineTo(32,30);path.lineTo(8,30);path.close();c.drawPath(path,p);c.drawLine(20,17,20,23,p);c.drawPoint(20,27,p);break;case "info":c.drawCircle(20,20,11,p);c.drawLine(20,19,20,26,p);c.drawPoint(20,14,p);break;case "light":c.drawCircle(20,17,8,p);c.drawLine(16,24,17,29,p);c.drawLine(24,24,23,29,p);c.drawLine(17,30,23,30,p);break;default:path.moveTo(11,27);path.lineTo(14,23);path.lineTo(14,17);path.cubicTo(14,8,26,8,26,17);path.lineTo(26,23);path.lineTo(29,27);path.close();c.drawPath(path,p);c.drawArc(17,27,23,33,0,180,false,p);}c.restore();
  }
 }
}
