package br.com.casanotify.tv;
import android.animation.ValueAnimator;import android.content.Context;import android.graphics.*;import android.media.*;import android.os.*;import android.provider.Settings;import android.speech.tts.TextToSpeech;import android.view.*;import org.json.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;
public final class OverlayManager {
 private final Context context;private final Prefs prefs;private final WindowManager windows;private final Handler main=new Handler(Looper.getMainLooper());
 private final ExecutorService images=new ThreadPoolExecutor(1,1,0,TimeUnit.SECONDS,new ArrayBlockingQueue<>(1),new ThreadPoolExecutor.DiscardOldestPolicy());
 private final Deque<Notice> queue=new ArrayDeque<>();private final Deque<JSONObject> history=new ArrayDeque<>();private final Set<ToneGenerator> tones=new HashSet<>();
 private MediaPlayer videoPlayer;private android.view.Surface videoSurface;private Notice current;private NoticeView view;private ValueAnimator countdown;private long generation;private volatile boolean destroyed;private TextToSpeech tts;private boolean ttsReady;
 public OverlayManager(Context c,Prefs p){context=c;prefs=p;windows=(WindowManager)c.getSystemService(Context.WINDOW_SERVICE);}
 private boolean muted(Notice n){JSONObject c=prefs.config();if(c.optBoolean("paused"))return true;if(n.urgent||!c.optBoolean("quiet_enabled"))return false;Calendar now=Calendar.getInstance();return QuietHours.contains(now.get(Calendar.HOUR_OF_DAY)*60+now.get(Calendar.MINUTE),c.optString("quiet_start"),c.optString("quiet_end"));}
 public LanServer.Response receive(Notice n)throws JSONException{if(!Settings.canDrawOverlays(context))return LanServer.Response.error(409,"Autorize aparecer sobre outros apps na TV.");if(muted(n)){record(n,"silenciado");return response(200,n,"suppressed");}boolean preempt=n.urgent||n.replace||(current!=null&&current.id.equals(n.id));for(Iterator<Notice> i=queue.iterator();i.hasNext();)if(i.next().id.equals(n.id))i.remove();if(!preempt&&current!=null&&queue.size()>=20)return LanServer.Response.error(429,"Fila cheia: limite de 20 avisos.");if(preempt&&current!=null){record(current,"substituído");removeCurrent();}if(current==null){if(!display(n))return LanServer.Response.error(409,"O Android bloqueou a janela do aviso.");return response(200,n,"displayed");}queue.addLast(n);return response(202,n,"queued");}
 private LanServer.Response response(int code,Notice n,String status)throws JSONException{return LanServer.Response.json(code,new JSONObject().put("id",n.id).put("status",status).put("queue",queue.size()).toString());}
 private boolean display(Notice n){if(destroyed)return false;android.util.DisplayMetrics m=new android.util.DisplayMetrics();windows.getDefaultDisplay().getRealMetrics(m);int margin=dp(n.margin);int width=Math.min(dp(n.width),Math.max(dp(160),m.widthPixels-2*margin));view=new NoticeView(context,n);
  WindowManager.LayoutParams lp=new WindowManager.LayoutParams(width,-2,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,PixelFormat.TRANSLUCENT);lp.alpha=(float)n.opacity;lp.gravity=(n.position.startsWith("top")?Gravity.TOP:n.position.startsWith("bottom")?Gravity.BOTTOM:Gravity.CENTER_VERTICAL)|(n.position.endsWith("left")?Gravity.LEFT:n.position.endsWith("right")?Gravity.RIGHT:Gravity.CENTER_HORIZONTAL);lp.x=n.position.endsWith("left")||n.position.endsWith("right")?margin:0;lp.y=n.position.startsWith("top")||n.position.startsWith("bottom")?margin:0;
  try{windows.addView(view,lp);}catch(RuntimeException e){view=null;record(n,"erro de sobreposição");return false;}current=n;long run=++generation;record(n,"exibido");
  if(!n.animation.equals("none")){view.setAlpha(0);if(n.animation.equals("slide"))view.setTranslationY(dp(n.position.startsWith("bottom")?16:-16));view.animate().alpha(1).translationY(0).setDuration(220).start();}
  countdown=ValueAnimator.ofInt(1000,0);countdown.setDuration(n.duration*1000L);countdown.setInterpolator(new android.view.animation.LinearInterpolator());countdown.addUpdateListener(a->{if(view!=null)view.progress.setProgress((int)a.getAnimatedValue());});countdown.start();main.postDelayed(()->{if(generation==run)finish();},n.duration*1000L);
  if(!n.imageUrl.isEmpty()){view.mediaStatus.setText("Carregando imagem…");view.mediaStatus.setVisibility(View.VISIBLE);loadImage(n,run);}if(n.sound&&n.volume>0)playSound(n.volume,n.tone);if(n.speak)speak(n,run);if(!n.videoUrl.isEmpty())startVideo(n,run);return true;
 }
 private void playSound(int volume,String tone){try{ToneGenerator t=new ToneGenerator(AudioManager.STREAM_NOTIFICATION,volume);tones.add(t);int kind=ToneGenerator.TONE_PROP_ACK,count=1,spacing=240;switch(tone){case "doorbell":kind=ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD;count=2;spacing=350;break;case "chime":kind=ToneGenerator.TONE_PROP_BEEP2;break;case "pulse":kind=ToneGenerator.TONE_PROP_BEEP;count=3;break;case "alarm":kind=ToneGenerator.TONE_CDMA_EMERGENCY_RINGBACK;count=2;spacing=550;break;case "digital":kind=ToneGenerator.TONE_DTMF_5;count=2;break;}final int selected=kind;for(int i=0;i<count;i++)main.postDelayed(()->{if(!destroyed&&tones.contains(t))t.startTone(selected,180);},i*spacing);main.postDelayed(()->{if(tones.remove(t))t.release();},count*spacing+300);}catch(RuntimeException ignored){}}
 private void startVideo(Notice n,long run){view.mediaStatus.setText("Conectando à câmera RTSP…");view.mediaStatus.setVisibility(View.VISIBLE);android.view.TextureView texture=view.video;texture.setSurfaceTextureListener(new android.view.TextureView.SurfaceTextureListener(){
  public void onSurfaceTextureAvailable(android.graphics.SurfaceTexture surface,int width,int height){if(generation!=run)return;try{videoSurface=new android.view.Surface(surface);MediaPlayer player=new MediaPlayer();videoPlayer=player;player.setSurface(videoSurface);player.setVolume(n.videoMuted?0:1,n.videoMuted?0:1);player.setOnPreparedListener(p->{if(generation!=run||videoPlayer!=p)return;p.start();if(view!=null)view.mediaStatus.setVisibility(View.GONE);});player.setOnErrorListener((p,what,extra)->{if(generation!=run||videoPlayer!=p)return true;if(view!=null){view.mediaStatus.setText("Câmera indisponível. Confira a rede, o endereço e o perfil H.264.");view.mediaStatus.setVisibility(View.VISIBLE);}releaseVideo();return true;});player.setDataSource(n.videoUrl);player.prepareAsync();main.postDelayed(()->{if(generation==run&&videoPlayer==player&&view!=null&&view.mediaStatus.getVisibility()==View.VISIBLE){view.mediaStatus.setText("Sem resposta da câmera. Confira a transmissão RTSP.");releaseVideo();}},12000);}catch(Exception e){if(view!=null)view.mediaStatus.setText("Não foi possível abrir esta câmera RTSP.");releaseVideo();}}
  public void onSurfaceTextureSizeChanged(android.graphics.SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(android.graphics.SurfaceTexture s){if(generation==run)releaseVideo();return true;}public void onSurfaceTextureUpdated(android.graphics.SurfaceTexture s){}
 });if(texture.isAvailable())texture.getSurfaceTextureListener().onSurfaceTextureAvailable(texture.getSurfaceTexture(),texture.getWidth(),texture.getHeight());}
 private void releaseVideo(){if(videoPlayer!=null){MediaPlayer player=videoPlayer;videoPlayer=null;player.setOnErrorListener(null);player.setOnPreparedListener(null);player.release();}if(videoSurface!=null){videoSurface.release();videoSurface=null;}}
 private void speak(Notice n,long run){if(tts==null){tts=new TextToSpeech(context,status->{if(destroyed)return;ttsReady=status==TextToSpeech.SUCCESS;if(ttsReady){int result=tts.setLanguage(new Locale("pt","BR"));ttsReady=result!=TextToSpeech.LANG_MISSING_DATA&&result!=TextToSpeech.LANG_NOT_SUPPORTED;if(ttsReady&&generation==run&&current!=null)speakNow(n);}});}else if(ttsReady)speakNow(n);}
 private void speakNow(Notice n){Bundle opts=new Bundle();opts.putFloat(TextToSpeech.Engine.KEY_PARAM_VOLUME,n.volume/100f);tts.speak(n.title+". "+n.message,TextToSpeech.QUEUE_FLUSH,opts,n.id);}
 private void loadImage(Notice n,long run){if(destroyed)return;images.execute(()->{Bitmap b=null;try{byte[] bytes=fetch(n.imageUrl);BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(options.outWidth<1||options.outHeight<1||options.outWidth>16000||options.outHeight>16000)throw new IOException();int sample=1;while(options.outWidth/sample>1280||options.outHeight/sample>1280)sample*=2;options.inJustDecodeBounds=false;options.inSampleSize=sample;b=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);}catch(Exception ignored){}final Bitmap result=b;main.post(()->{if(destroyed||generation!=run||view==null){if(result!=null)result.recycle();return;}if(result!=null){view.image.setImageBitmap(result);view.image.setVisibility(View.VISIBLE);view.mediaStatus.setVisibility(View.GONE);}else{view.mediaStatus.setText("Imagem indisponível. Verifique a URL.");view.mediaStatus.setVisibility(View.VISIBLE);}if(n.imageRefresh>=5)main.postDelayed(()->{if(!destroyed&&generation==run&&current!=null)loadImage(n,run);},n.imageRefresh*1000L);});});}
 private byte[] fetch(String location)throws Exception{String next=location;for(int hop=0;hop<4;hop++){Notice.validateImageUrl(next);HttpURLConnection c=(HttpURLConnection)new URL(next).openConnection();c.setConnectTimeout(3500);c.setReadTimeout(3500);c.setUseCaches(false);c.setInstanceFollowRedirects(false);c.setRequestProperty("Accept","image/*");try{int status=c.getResponseCode();if(status>=300&&status<400){String r=c.getHeaderField("Location");if(r==null)throw new IOException();next=new URL(new URL(next),r).toString();continue;}if(status!=200||c.getContentLengthLong()>4*1024*1024)throw new IOException();long end=System.nanoTime()+10_000_000_000L;try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];int count;while((count=in.read(buffer))!=-1){if(Thread.currentThread().isInterrupted()||System.nanoTime()>end||out.size()+count>4*1024*1024)throw new IOException();out.write(buffer,0,count);}return out.toByteArray();}}finally{c.disconnect();}}throw new IOException();}
 private int dp(int v){return Math.round(v*context.getResources().getDisplayMetrics().density);}
 private void removeCurrent(){generation++;releaseVideo();if(countdown!=null){countdown.cancel();countdown=null;}if(tts!=null)tts.stop();if(view!=null){view.animate().cancel();try{windows.removeViewImmediate(view);}catch(RuntimeException ignored){}view=null;}current=null;}
 private void finish(){removeCurrent();while(!queue.isEmpty()){Notice n=queue.removeFirst();if(muted(n)){record(n,"silenciado");continue;}if(display(n))break;}}
 public void clear(String id){if(id==null||id.isEmpty()){queue.clear();removeCurrent();return;}queue.removeIf(n->n.id.equals(id));if(current!=null&&current.id.equals(id))finish();}
 public JSONArray history(){return new JSONArray(history);}public JSONObject state()throws JSONException{return new JSONObject().put("active",current==null?JSONObject.NULL:current.id).put("queued",queue.size());}
 private void record(Notice n,String result){try{history.addFirst(new JSONObject().put("time",System.currentTimeMillis()).put("title",n.title).put("result",result).put("id",n.id));while(history.size()>30)history.removeLast();}catch(JSONException ignored){}}
 public void destroy(){destroyed=true;queue.clear();removeCurrent();main.removeCallbacksAndMessages(null);for(ToneGenerator t:tones)t.release();tones.clear();images.shutdownNow();if(tts!=null){tts.shutdown();tts=null;}history.clear();}
}
