package br.com.casanotify.tv;
import android.app.*;import android.content.*;import android.content.pm.*;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;

public final class PhoneActivity extends Activity {
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private SharedPreferences settings;private LinearLayout apps;private TextView state;private JSONObject target;
    public void onCreate(Bundle b){Ui.theme(this);super.onCreate(b);settings=getSharedPreferences("phone",MODE_PRIVATE);LinearLayout p=Ui.page(this,"Notificações do celular");p.addView(Ui.text(this,"Instale este mesmo APK no seu celular Android. Selecione os apps que poderão enviar avisos à TV. O envio começa somente depois que você habilitar o recurso e autorizar o acesso no Android.",16));state=Ui.text(this,"",15);p.addView(state);
        EditText host=Ui.input(this,p,"IP da TV",InputType.TYPE_CLASS_TEXT);try{String saved=new SecretStore(this,"phone_target").read();if(!saved.isEmpty()){target=new JSONObject(saved);host.setText(target.optString("host"));}}catch(Exception e){Ui.toast(this,"Vincule a TV novamente.");}
        Ui.button(this,p,"Encontrar TV e conferir certificado",()->{String address=host.getText().toString();state.setText("Procurando TV…");worker.execute(()->{try{JSONObject info=PhoneApi.discover(address);onUi(()->approve(info));}catch(Exception e){onUi(()->Ui.message(this,"Conexão","Não foi possível acessar a TV. Confira o IP, a rede e o APK 2.0.0."));}});});
        Ui.button(this,p,"Autorizar acesso às notificações",()->{if(!Ui.accepted(this)){Ui.termsDialog(this,true,()->{});return;}try{startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS));}catch(Exception e){Ui.message(this,"Permissão","Abra Configurações → Acesso especial → Acesso a notificações no seu celular.");}});
        Switch enabled=new Switch(this);enabled.setText("Enviar notificações dos apps selecionados");enabled.setChecked(settings.getBoolean("enabled",false));enabled.setOnCheckedChangeListener((v,on)->{if(on&&(target==null||!Ui.accepted(this))){enabled.setChecked(false);Ui.message(this,"Antes de ativar","Vincule a TV e aceite os termos. Depois autorize o acesso a notificações no Android.");return;}settings.edit().putBoolean("enabled",on).apply();});p.addView(enabled);
        Switch content=new Switch(this);content.setText("Incluir título e conteúdo das mensagens");content.setChecked(settings.getBoolean("content",false));content.setOnCheckedChangeListener((v,on)->settings.edit().putBoolean("content",on).apply());p.addView(content);p.addView(Ui.text(this,"Com conteúdo desligado, a TV mostra apenas o nome do aplicativo. Outras pessoas próximas à TV podem ler as mensagens. Códigos e notificações sensíveis são filtrados quando identificados.",14));
        Ui.button(this,p,"Enviar teste do celular",()->worker.execute(()->{try{if(target==null)throw new Exception();PhoneApi.call(target,"/api/notify",new JSONObject().put("id","phone-test").put("title","Celular conectado!").put("message","Obrigado por conectar seu celular ao CasaNotify TV."));onUi(()->Ui.toast(this,"Teste enviado."));}catch(Exception e){onUi(()->Ui.toast(this,"Não foi possível enviar o teste. Confira o vínculo e a rede."));}}));
        Ui.button(this,p,"Desvincular este celular",()->{new SecretStore(this,"phone_target").delete();target=null;settings.edit().putBoolean("enabled",false).apply();enabled.setChecked(false);Ui.toast(this,"Vínculo local removido. Você pode revogar a credencial também no painel da TV.");});
        p.addView(Ui.text(this,"Aplicativos autorizados",21));apps=new LinearLayout(this);apps.setOrientation(LinearLayout.VERTICAL);p.addView(apps);loadApps();Ui.button(this,p,"Termos e privacidade",()->Ui.termsDialog(this,!Ui.accepted(this),null));Ui.button(this,p,"Voltar",this::finish);
    }
    private void onUi(Runnable action){runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())action.run();});}
    private void approve(JSONObject info){if(isFinishing())return;new AlertDialog.Builder(this).setTitle("Confira na sua TV").setMessage("TV: "+info.optString("device_name")+"\n\nAbra ‘Segurança do painel’ na TV e compare toda a impressão digital:\n\n"+info.optString("tls_fingerprint")+"\n\nContinue somente se forem iguais.").setPositiveButton("Certificado igual",(d,w)->pair(info)).setNegativeButton("Cancelar",null).show();}
    private void pair(JSONObject info){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);int pad=Ui.dp(this,20);p.setPadding(pad,pad,pad,pad);p.addView(Ui.text(this,"Na TV, abra ‘Vincular celular para avisos’ e informe o código de seis números.",16));EditText code=Ui.input(this,p,"Código da TV",InputType.TYPE_CLASS_NUMBER);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Vincular celular").setView(p).setPositiveButton("Vincular",null).setNegativeButton("Cancelar",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{String value=code.getText().toString().trim();if(!value.matches("[0-9]{6}")){code.setError("Digite seis números");return;}dialog.getButton(-1).setEnabled(false);worker.execute(()->{try{JSONObject response=PhoneApi.call(info,"/api/pair",new JSONObject().put("code",value).put("client","phone").put("name",Build.MODEL));info.put("token",response.getString("token"));new SecretStore(this,"phone_target").write(info.toString());target=info;onUi(()->{dialog.dismiss();Ui.message(this,"Obrigado!","Seu celular foi vinculado. Escolha os aplicativos e ative o envio quando desejar.");refresh();});}catch(Exception e){onUi(()->{dialog.getButton(-1).setEnabled(true);code.setError("Confira o código, a data da TV e o certificado.");});}});}));dialog.show();}
    private void loadApps(){worker.execute(()->{List<ResolveInfo> list=getPackageManager().queryIntentActivities(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER),0);list.sort(Comparator.comparing(a->a.loadLabel(getPackageManager()).toString().toLowerCase(Locale.ROOT)));onUi(()->{if(isFinishing())return;Set<String> seen=new HashSet<>();for(ResolveInfo item:list){String pkg=item.activityInfo.packageName;if(pkg.equals(getPackageName())||!seen.add(pkg))continue;CheckBox check=new CheckBox(this);check.setText(item.loadLabel(getPackageManager()));check.setChecked(settings.getStringSet("apps",Collections.emptySet()).contains(pkg));check.setOnCheckedChangeListener((v,on)->{Set<String> selected=new HashSet<>(settings.getStringSet("apps",Collections.emptySet()));if(on)selected.add(pkg);else selected.remove(pkg);settings.edit().putStringSet("apps",selected).apply();});apps.addView(check);}if(seen.isEmpty())apps.addView(Ui.text(this,"Nenhum aplicativo visível. Use este recurso no celular.",16));});});}
    protected void onResume(){super.onResume();refresh();}
    private void refresh(){if(state!=null){String listeners=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");boolean permitted=listeners!=null&&listeners.contains(new ComponentName(this,PhoneNotificationService.class).flattenToString());state.setText((target==null?"TV não vinculada":"TV vinculada")+" · "+(permitted?"Acesso autorizado":"Autorize o acesso às notificações")+"\n"+settings.getString("last_status","Nenhum envio realizado"));}}
    protected void onDestroy(){worker.shutdownNow();super.onDestroy();}
}
