package br.com.casanotify.tv;
import android.content.*;import org.json.*;import java.security.SecureRandom;import java.util.*;
public final class Prefs {
 public static final int PORT=8765,SECURE_PORT=8766;private final SharedPreferences p;private final SecretStore secrets;
 public Prefs(Context c){p=c.getSharedPreferences("casanotify",Context.MODE_PRIVATE);secrets=new SecretStore(c,"ha_token");}
 public synchronized String token(){try{String t=secrets.read();if(t.isEmpty()){t=p.getString("token","");if(t.isEmpty())return rotateToken();secrets.write(t);}if(p.contains("token"))p.edit().remove("token").commit();return t;}catch(Exception e){throw new IllegalStateException("Não foi possível ler a credencial protegida.",e);}}
 public synchronized String rotateToken(){byte[] b=new byte[24];new SecureRandom().nextBytes(b);StringBuilder s=new StringBuilder();for(byte v:b)s.append(String.format(Locale.ROOT,"%02x",v&255));try{secrets.write(s.toString());p.edit().remove("token").commit();return s.toString();}catch(Exception e){throw new IllegalStateException("Não foi possível salvar a credencial protegida.",e);}}
 public synchronized String deviceId(){String id=p.getString("device_id", "");if(id.isEmpty()){id=UUID.randomUUID().toString();p.edit().putString("device_id",id).commit();}return id;}
 public boolean quietActive(){JSONObject c=config();if(!c.optBoolean("quiet_enabled"))return false;Calendar now=Calendar.getInstance();return QuietHours.contains(now.get(Calendar.HOUR_OF_DAY)*60+now.get(Calendar.MINUTE),c.optString("quiet_start"),c.optString("quiet_end"));}
 public boolean enabled(){return p.getBoolean("enabled",false);}public void enabled(boolean b){p.edit().putBoolean("enabled",b).commit();}
 public JSONObject config(){try{JSONObject c=new JSONObject(p.getString("config","{\"device_name\":\"TV da sala\",\"defaults\":{},\"auto_start\":false,\"paused\":false,\"quiet_enabled\":false,\"quiet_start\":\"22:00\",\"quiet_end\":\"07:00\"}"));if(!c.has("ui_theme"))c.put("ui_theme","system");if(!c.has("startup_animation"))c.put("startup_animation",true);return c;}catch(JSONException e){throw new IllegalStateException(e);}}
 public JSONObject defaults(){return config().optJSONObject("defaults");}
 public synchronized JSONObject update(JSONObject u)throws JSONException{Notice.rejectUnknown(u,new HashSet<>(Arrays.asList("device_name","defaults","auto_start","paused","quiet_enabled","quiet_start","quiet_end","ui_theme","startup_animation")));JSONObject n=config();Iterator<String> i=u.keys();while(i.hasNext()){String k=i.next();n.put(k,u.get(k));}if(Notice.string(n,"device_name","TV da sala",60).trim().isEmpty())throw new IllegalArgumentException("Informe o nome da TV.");for(String k:new String[]{"auto_start","paused","quiet_enabled","startup_animation"})Notice.bool(n,k,false);Notice.option(n,"ui_theme","system",new String[]{"light","dark","system"});QuietHours.minutes(Notice.string(n,"quiet_start","22:00",5));QuietHours.minutes(Notice.string(n,"quiet_end","07:00",5));if(!(n.get("defaults") instanceof JSONObject))throw new IllegalArgumentException("defaults precisa ser um objeto.");Notice.rejectUnknown(n.getJSONObject("defaults"),Notice.STYLE);new Notice(new JSONObject(),n.getJSONObject("defaults"));p.edit().putString("config",n.toString()).commit();return n;}
}
