package br.com.casanotify.tv;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;import org.json.*;

public final class ProfileActivity extends Activity {
    private Prefs prefs;
    public void onCreate(Bundle b){Ui.theme(this);super.onCreate(b);prefs=new Prefs(this);LinearLayout p=Ui.page(this,"Perfil, aparência e segurança");
        try{JSONObject profile=SecretStore.accounts(this).profile();String name=profile.optString("display_name","");p.addView(Ui.text(this,name.isEmpty()?"Crie sua conta pelo aplicativo CasaNotify Controle.":"Obrigado, "+name+"! Sua casa tem o seu jeito.",19));}catch(Exception ignored){}
        p.addView(Ui.text(this,"Tema do aplicativo",19));Spinner themes=new Spinner(this);String[] ids={"system","light","dark"};themes.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Seguir o sistema","Claro","Escuro"}));themes.setSelection(java.util.Arrays.asList(ids).indexOf(prefs.config().optString("ui_theme","system")));p.addView(themes);
        Switch animation=new Switch(this);animation.setText("Animação ao abrir o aplicativo");animation.setChecked(prefs.config().optBoolean("startup_animation",true));p.addView(animation);Ui.button(this,p,"Salvar tema e animação",()->{try{prefs.update(new JSONObject().put("ui_theme",ids[themes.getSelectedItemPosition()]).put("startup_animation",animation.isChecked()));recreate();}catch(Exception e){Ui.toast(this,"Não foi possível salvar.");}});
        p.addView(Ui.text(this,"Logo e plano de fundo",19));p.addView(Ui.text(this,"No app CasaNotify Controle, abra ‘Minha marca’. Você pode enviar uma imagem, recortar, girar, ajustar o brilho e salvar como logo ou fundo. O logo aparece dentro do aplicativo; o ícone instalado na tela inicial permanece o do CasaNotify TV.",16));
        Ui.button(this,p,"Identificação segura da TV / Segurança do painel",()->{try{String fp=LocalTls.fingerprint();TextView t=Ui.text(this,"Endereço: "+NetworkInfo.primary()+"\n\nCertificado SHA-256:\n"+fp.replaceAll("(.{4})(?!$)","$1 ")+"\n\nCompare todos os grupos com o app CasaNotify Controle no primeiro vínculo. O app mantém esse certificado salvo e recusa uma identidade diferente. O código inicial aprova o vínculo deste controle; depois, use apenas usuário e senha. O Home Assistant tem vínculo separado.",16);t.setTextIsSelectable(true);int pad=Ui.dp(this,20);t.setPadding(pad,pad,pad,pad);new AlertDialog.Builder(this).setTitle("HTTPS da sua TV").setView(t).setPositiveButton("Fechar",null).show();}catch(Exception e){Ui.message(this,"HTTPS","Não foi possível ler o certificado local.");}});
        Ui.button(this,p,"Vincular controle / criar conta",()->code("control"));
        Ui.button(this,p,"Vincular celular para avisos",()->code("phone"));
        Ui.button(this,p,"Redefinir conta de acesso",()->new AlertDialog.Builder(this).setTitle("Apagar a conta de acesso?").setMessage("Revoga os controles vinculados, encerra as sessões e remove a conta desta TV. Depois será necessário cadastrar usuário e senha novamente. Câmeras e vínculos do Home Assistant continuam configurados.").setPositiveButton("Redefinir",(d,w)->{try{PhoneTokens.get(this).revokeControls();SecretStore.accounts(this).reset();Ui.message(this,"Conta removida","Gere um novo código e cadastre a conta pelo CasaNotify Controle.");}catch(Exception e){Ui.toast(this,"Não foi possível redefinir.");}}).setNegativeButton("Cancelar",null).show());
        Ui.button(this,p,"Revogar controles e celulares vinculados",()->new AlertDialog.Builder(this).setTitle("Revogar controles e celulares?").setMessage("Os controles e os celulares de espelhamento precisarão ser vinculados novamente. O Home Assistant continua vinculado.").setPositiveButton("Revogar",(d,w)->{try{PhoneTokens.get(this).revoke("");Ui.toast(this,"Controles e celulares revogados.");}catch(Exception e){Ui.toast(this,"Não foi possível revogar.");}}).setNegativeButton("Cancelar",null).show());
        Ui.button(this,p,"Termos e privacidade",()->Ui.termsDialog(this,false,null));Ui.button(this,p,"Voltar",this::finish);
    }
    private void code(String kind){if(!NotifyService.running){Ui.toast(this,"Ative o receptor primeiro.");return;}String value=Pairing.issue(kind);TextView t=Ui.text(this,value.substring(0,3)+" "+value.substring(3),40);t.setGravity(android.view.Gravity.CENTER);new AlertDialog.Builder(this).setTitle(kind.equals("control")?"Vincular controle":"Vincular celular para avisos").setMessage(kind.equals("control")?"No celular, abra CasaNotify Controle, conecte à TV e crie sua conta. Este código autoriza o aplicativo de controle e vale por dois minutos. O login usa apenas usuário e senha.":"Na edição CasaNotify Celular, abra Menu → Avisos dos aplicativos, confira o certificado e digite este código. Válido por dois minutos.").setView(t).setPositiveButton("Concluído",(d,w)->Pairing.cancel()).setOnCancelListener(d->Pairing.cancel()).show();}
}
