package br.com.casanotify.tv;
import android.app.*;import android.content.*;import android.content.res.Configuration;import android.graphics.Color;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;

public final class Ui {
    public static boolean dark(Context c){String t=new Prefs(c).config().optString("ui_theme","system");return t.equals("dark")||t.equals("system")&&(c.getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK)==Configuration.UI_MODE_NIGHT_YES;}
    public static void theme(Activity a){a.setTheme(dark(a)?R.style.AppTheme:R.style.LightTheme);}
    public static int dp(Context c,int n){return Math.round(c.getResources().getDisplayMetrics().density*n);}
    public static LinearLayout page(Activity a,String title){ScrollView scroll=new ScrollView(a);scroll.setFillViewport(true);background(a,scroll);LinearLayout p=new LinearLayout(a);p.setOrientation(LinearLayout.VERTICAL);int pad=dp(a,26);p.setPadding(pad,pad,pad,pad);scroll.addView(p);TextView t=text(a,title,26);p.addView(t);a.setContentView(scroll);return p;}
    public static void background(Context c,View view){android.graphics.Bitmap image=new MediaAssets(c).bitmap("background");int color=dark(c)?0xff0c1116:0xfff1f5ef;if(image==null){view.setBackgroundColor(color);return;}android.graphics.drawable.BitmapDrawable photo=new android.graphics.drawable.BitmapDrawable(c.getResources(),image);photo.setGravity(Gravity.FILL);android.graphics.drawable.ColorDrawable shade=new android.graphics.drawable.ColorDrawable(dark(c)?0xe60c1116:0xe6f1f5ef);view.setBackground(new android.graphics.drawable.LayerDrawable(new android.graphics.drawable.Drawable[]{photo,shade}));}
    public static TextView text(Context c,String s,int size){TextView t=new TextView(c);t.setText(s);t.setTextSize(size);t.setTextColor(dark(c)?0xfff0f3f4:0xff15251d);t.setPadding(0,dp(c,8),0,dp(c,8));return t;}
    public static Button button(Activity a,LinearLayout p,String label,Runnable action){Button b=new Button(a);b.setText(label);b.setAllCaps(false);b.setMinHeight(dp(a,48));b.setOnClickListener(v->action.run());p.addView(b,new LinearLayout.LayoutParams(-1,-2));return b;}
    public static EditText input(Activity a,LinearLayout p,String label,int type){p.addView(text(a,label,15));EditText e=new EditText(a);e.setSingleLine(true);e.setInputType(type);p.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
    public static String terms(Context c){try(InputStream in=c.getAssets().open("terms.txt");ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return new String(out.toByteArray(),StandardCharsets.UTF_8);}catch(Exception e){return "Não foi possível abrir os termos. Reinstale o aplicativo.";}}
    public static boolean accepted(Context c){return c.getSharedPreferences("consent",Context.MODE_PRIVATE).getString("version","").equals(AccountManager.TERMS_VERSION);}
    public static void termsDialog(Activity a,boolean required,Runnable after){ScrollView scroll=new ScrollView(a);TextView text=text(a,terms(a),16);int pad=dp(a,20);text.setPadding(pad,pad,pad,pad);scroll.addView(text);AlertDialog.Builder builder=new AlertDialog.Builder(a).setTitle("Termos e privacidade").setView(scroll).setPositiveButton(required?"Li e aceito":"Fechar",(d,w)->{if(required)a.getSharedPreferences("consent",Context.MODE_PRIVATE).edit().putString("version",AccountManager.TERMS_VERSION).putLong("accepted_at",System.currentTimeMillis()).apply();if(after!=null)after.run();});if(required)builder.setCancelable(false).setNegativeButton("Não aceitar",(d,w)->{new Prefs(a).enabled(false);a.stopService(new Intent(a,NotifyService.class));a.finish();});builder.show();}
    public static void message(Activity a,String title,String value){new AlertDialog.Builder(a).setTitle(title).setMessage(value).setPositiveButton("Entendi",null).show();}
    public static void toast(Context c,String s){Toast.makeText(c,s,Toast.LENGTH_LONG).show();}
}
