package br.com.casanotify.tv;
import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.*;import android.os.Build;import android.provider.Settings;import android.text.InputType;import android.widget.*;

/** Android-managed IKEv2 profile, with system consent. No VPN server is bundled. */
public final class VpnActivity extends Activity {
    private TextView state;private boolean pending;
    public static boolean active(Context c){ConnectivityManager m=(ConnectivityManager)c.getSystemService(Context.CONNECTIVITY_SERVICE);if(m==null)return false;for(Network n:m.getAllNetworks()){NetworkCapabilities caps=m.getNetworkCapabilities(n);if(caps!=null&&caps.hasTransport(NetworkCapabilities.TRANSPORT_VPN))return true;}return false;}
    public void onCreate(android.os.Bundle b){Ui.theme(this);super.onCreate(b);LinearLayout p=Ui.page(this,"VPN e rede privada");state=Ui.text(this,"",17);p.addView(state);p.addView(Ui.text(this,"Use seu próprio servidor ou provedor. O CasaNotify não fornece servidor VPN. Uma VPN pode bloquear o acesso à rede local; a descoberta automática geralmente não atravessa a VPN.",16));Ui.button(this,p,"Abrir VPNs do Android",()->{try{startActivity(new Intent(Settings.ACTION_VPN_SETTINGS));}catch(Exception e){Ui.message(this,"VPN","Esta TV não oferece a tela de VPN do Android.");}});
        if(Build.VERSION.SDK_INT>=30&&getPackageManager().hasSystemFeature(PackageManager.FEATURE_IPSEC_TUNNELS)){
            p.addView(Ui.text(this,"Conexão IKEv2/IPsec do CasaNotify",21));EditText server=Ui.input(this,p,"Servidor (domínio ou IP)",InputType.TYPE_CLASS_TEXT),identity=Ui.input(this,p,"Identidade IKEv2",InputType.TYPE_CLASS_TEXT),username=Ui.input(this,p,"Usuário (para autenticação por senha)",InputType.TYPE_CLASS_TEXT),password=Ui.input(this,p,"Senha do usuário",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD),psk=Ui.input(this,p,"Ou chave pré-compartilhada (PSK)",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);
            p.addView(Ui.text(this,"Preencha usuário e senha OU uma PSK fornecida pelo seu administrador. Para usuário/senha, o certificado do servidor deve ser confiável para o Android. As credenciais do perfil são gerenciadas pelo sistema.",14));
            Ui.button(this,p,"Configurar e solicitar conexão",()->{try{String host=server.getText().toString().trim(),id=identity.getText().toString().trim(),user=username.getText().toString(),pass=password.getText().toString(),secret=psk.getText().toString();if(host.isEmpty()||id.isEmpty()||host.contains("://"))throw new IllegalArgumentException("Informe servidor e identidade.");if(!secret.isEmpty()&&(!user.isEmpty()||!pass.isEmpty()))throw new IllegalArgumentException("Escolha senha de usuário OU PSK.");Ikev2VpnProfile.Builder builder=new Ikev2VpnProfile.Builder(host,id);if(!secret.isEmpty())builder.setAuthPsk(secret.getBytes(java.nio.charset.StandardCharsets.UTF_8));else{if(user.isEmpty()||pass.isEmpty())throw new IllegalArgumentException("Informe as credenciais fornecidas pelo seu servidor.");builder.setAuthUsernamePassword(user,pass,null);}Intent consent=getSystemService(VpnManager.class).provisionVpnProfile(builder.build());password.setText("");psk.setText("");if(consent!=null){pending=true;startActivityForResult(consent,44);}else connect();}catch(Exception e){Ui.message(this,"VPN",e instanceof IllegalArgumentException?e.getMessage():"O Android não conseguiu provisionar o perfil. Confira os dados e o suporte do aparelho.");}});
            Ui.button(this,p,"Conectar perfil já configurado",this::connect);Ui.button(this,p,"Desconectar perfil do CasaNotify",()->{try{getSystemService(VpnManager.class).stopProvisionedVpnProfile();refresh();}catch(Exception e){Ui.toast(this,"Não há perfil ativo do CasaNotify.");}});
            Ui.button(this,p,"Remover perfil do CasaNotify",()->new AlertDialog.Builder(this).setTitle("Remover VPN?").setMessage("Remove somente o perfil configurado por este aplicativo.").setPositiveButton("Remover",(d,w)->{try{getSystemService(VpnManager.class).deleteProvisionedVpnProfile();refresh();}catch(Exception e){Ui.toast(this,"Não foi possível remover o perfil.");}}).setNegativeButton("Cancelar",null).show());
        }else p.addView(Ui.text(this,"IKEv2 integrado exige Android 11+ com suporte IPsec. Você pode usar uma VPN já instalada, como WireGuard, pelas configurações do Android.",16));
        Ui.button(this,p,"Voltar",this::finish);
    }
    private void connect(){if(Build.VERSION.SDK_INT<30)return;try{if(Build.VERSION.SDK_INT>=33)getSystemService(VpnManager.class).startProvisionedVpnProfileSession();else getSystemService(VpnManager.class).startProvisionedVpnProfile();Ui.toast(this,"Conexão solicitada ao Android. Confira o estado da VPN.");refresh();}catch(Exception e){Ui.message(this,"VPN","Configure o perfil e autorize a conexão antes de iniciar.");}}
    protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==44&&pending){pending=false;if(result==RESULT_OK)connect();else Ui.toast(this,"Conexão VPN não autorizada.");}}
    protected void onResume(){super.onResume();refresh();}
    private void refresh(){if(state!=null)state.setText(active(this)?"VPN ativa no Android":"Nenhuma VPN ativa no Android");}
}
