'use strict';
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),receiver=require('./mock-receiver.cjs');
(async()=>{const output=process.env.CASANOTIFY_PREVIEWS||'/tmp/casanotify-previews';fs.mkdirSync(output,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chromium',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1080},colorScheme:'light'});const page=await context.newPage(),mock=receiver(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://casanotify.test/**',async route=>{const req=route.request(),name=new URL(req.url()).pathname;const asset=name==='/'?'index.html':name.slice(1);if(['index.html','panel.js','control.js','panel.css','terms.txt'].includes(asset)){await route.fulfill({status:200,body:fs.readFileSync(path.join(__dirname,'../app/src/main/assets',asset)),contentType:asset.endsWith('.js')?'application/javascript':asset.endsWith('.css')?'text/css':asset.endsWith('.txt')?'text/plain':'text/html'});return;}const r=await mock.request(req.url(),{method:req.method(),body:req.postData(),headers:req.headers()});await route.fulfill({status:r.status,json:r.data});});
await page.goto('https://casanotify.test/');await page.locator('#register-form').waitFor({state:'visible'});await page.screenshot({path:path.join(output,'01-cadastro.png'),fullPage:true});
for(const [id,value] of Object.entries({'setup-code':'123456','full-name':'Douglas','new-username':'douglas','new-password':'long test password','confirm-password':'long test password'}))await page.locator('#'+id).fill(value);await page.locator('#terms-accepted').check();await page.locator('#register-form button').click();await page.locator('#app').waitFor({state:'visible'});assert.match(await page.locator('#thanks-title').textContent(),/Douglas/);await page.locator('#close-thanks').click();await page.screenshot({path:path.join(output,'02-painel-claro.png'),fullPage:true});
await page.locator('[data-tab=branding]').click();const png=await page.locator('.brand').screenshot();await page.locator('#asset-file').setInputFiles({name:'marca-teste.png',mimeType:'image/png',buffer:png});await page.locator('#asset-save').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('asset-save').disabled);await page.locator('#asset-rotate').click();await page.locator('#asset-save').click();await page.waitForFunction(()=>document.getElementById('toast').textContent.includes('Imagem salva'));const upload=mock.state.calls.find(c=>c.path==='/api/media');assert.ok(JSON.parse(upload.opts.body).data.startsWith('data:image/png;base64,'));await page.screenshot({path:path.join(output,'03-editor-imagem.png'),fullPage:true});
await page.locator('[data-tab=appearance]').click();await page.locator('#ui-theme').selectOption('dark');await page.locator('#appearance-form button[type=submit]').click();await page.locator('[data-tab=compose]').click();await page.screenshot({path:path.join(output,'04-painel-escuro.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});for(const tab of ['compose','appearance','integration','cameras','branding','security']){await page.locator('[data-tab='+tab+']').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Overflow mobile: '+tab);}await page.locator('[data-tab=security]').click();await page.screenshot({path:path.join(output,'05-celular-conta.png'),fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: Chromium desktop/mobile, cadastro completo, edição e upload de PNG, temas claro/escuro, seis seções sem rolagem horizontal e sem erros JavaScript.');})().catch(e=>{console.error(e);process.exit(1);});
