'use strict';
const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),receiver=require('./mock-receiver.cjs');
const source=path.join(__dirname,'../app/src/main/assets'),mock=receiver(),native=process.argv.includes('--native');let window;
const turn=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
async function launch(){const dom=new JSDOM(fs.readFileSync(path.join(source,'index.html'),'utf8'),{url:native?'https://app.casanotify.local':'https://192.168.1.50:8766',runScripts:'outside-only',pretendToBeVisual:true});window=dom.window;window.scrollTo=()=>{};window.matchMedia=()=>({matches:false,addEventListener(){}});window.AbortController=global.AbortController;window.URL.createObjectURL=()=> 'blob:test';window.URL.revokeObjectURL=()=>{};window.sessionStorage.setItem('casanotify-key','legacy-must-be-removed');window.fetch=native?()=>{throw new Error('Native UI must not use network fetch');}:mock.request;
if(native){window.eval(fs.readFileSync(path.join(source,'control.js'),'utf8'));const port={onmessage:null,postMessage:async raw=>{const q=JSON.parse(raw);let result;if(q.command==='api'){const r=await mock.request(q.path,{method:q.method,body:q.body,headers:{'X-CasaNotify-CSRF':q.csrf}});result={status:r.status,data:r.data};}else if(q.command==='copy'){result={};}else if(q.command==='pickImage'){result={};}else throw new Error('Unexpected native command');port.onmessage({data:JSON.stringify({id:q.id,result})});}};window.dispatchEvent(new window.MessageEvent('message',{data:'casanotify-native',ports:[port]}));}
window.eval(fs.readFileSync(path.join(source,'panel.js'),'utf8'));await turn();return dom;}
const $=id=>window.document.getElementById(id);function input(id,v){$(id).value=String(v);$(id).dispatchEvent(new window.Event('input',{bubbles:true}));}function check(id,v){$(id).checked=v;$(id).dispatchEvent(new window.Event('change',{bubbles:true}));}async function click(s){window.document.querySelector(s).click();await turn();}async function submit(id){const form=$(id),b=form.querySelector('button:not([type=button])');form.dispatchEvent(new window.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:b}));await turn();}
async function main(){let dom=await launch();assert.equal($('register-form').hidden,false);assert.equal(window.sessionStorage.getItem('casanotify-key'),null);input('full-name','Douglas');input('new-username','douglas');input('new-password','long test password');input('confirm-password','mismatch');check('terms-accepted',true);await submit('register-form');assert.match($('login-error').textContent,/iguais/);input('confirm-password','long test password');await submit('register-form');assert.equal(JSON.parse(mock.state.calls.find(c=>c.path==='/auth/register').opts.body).remember,true);assert.equal($('new-password').value,'');assert.equal($('otp'),null);assert.equal($('totp-form'),null);assert.equal($('app').hidden,false);assert.equal($('thanks').hidden,false);assert.match($('thanks-title').textContent,/Douglas/);assert.equal($('device-label').textContent,'TV de teste');if(native){assert.equal($('asset-file').hidden,true);assert.ok(window.CasaControl);}assert.equal($('notice-icon').options.length,21);assert.equal($('notice-tone').options.length,16);
const message='Olá "TV"\nLinha 2 — <img src=x onerror=alert(1)>';input('notice-message',message);await submit('notice-form');assert.equal(mock.state.notice.message,message);assert.equal($('preview-message').children.length,0);assert.equal(mock.state.notice.tone,'soft');
await click('[data-tab=appearance]');await click('#theme-options [data-theme=ocean]');await click('#position-options [data-position=bottom_left]');input('duration',17);input('device-name','TV do quarto');check('default-sound',true);input('ui-theme','dark');$('ui-theme').dispatchEvent(new window.Event('change'));input('default-tone','digital');$('default-tone').dispatchEvent(new window.Event('change'));check('startup-animation',false);await submit('appearance-form');assert.equal(mock.state.config.defaults.tone,'digital');assert.equal(mock.state.config.ui_theme,'dark');assert.equal(mock.state.config.startup_animation,false);assert.equal(mock.state.config.defaults.duration,17);assert.equal(window.document.documentElement.dataset.theme,'dark');
assert.equal($('camera-form'),null);assert.equal($('camera-select'),null);assert.equal($('vpn-status'),null);assert.equal(window.document.querySelector('[data-tab=cameras]'),null);input('image-url','http://camera.test/picture.jpg');await submit('notice-form');assert.equal(mock.state.notice.image_url,'http://camera.test/picture.jpg');assert.equal('camera_id' in mock.state.notice,false);assert.equal('video_url' in mock.state.notice,false);
await click('[data-tab=integration]');await click('#use-current');assert.match($('yaml-test').textContent,/casanotify_tv.send_notification/);assert.match($('yaml-test').textContent,/image_url: "http:\/\/camera.test\/picture.jpg"/);assert.equal($('yaml-test').textContent.includes('Bearer'),false);assert.match($('ha-fingerprint').textContent,/abab/);
await click('[data-tab=security]');input('profile-name','Douglas & família');await submit('profile-form');assert.match($('personal-footer').textContent,/Douglas & família/);await click('#phone-list button');assert.equal(mock.state.phones.length,0);await click('[data-tab=activity]');assert.equal(window.document.querySelectorAll('.history-row').length,2);await click('#clear-notices');assert.match($('toast').textContent,/esvaziada/);
await click('#logout');assert.equal($('app').hidden,true);input('username','douglas');input('password','incorrect');await submit('login-form');assert.match($('login-error').textContent,/inválido/);input('password','long test password');check('remember-login',false);await submit('login-form');assert.equal(JSON.parse(mock.state.calls.filter(c=>c.path==='/auth/login').at(-1).opts.body).remember,false);assert.equal($('app').hidden,false);dom.window.close();if(native)mock.state.session=false;dom=await launch();if(native){assert.equal($('app').hidden,true);input('username','douglas');input('password','long test password');await submit('login-form');}assert.equal($('app').hidden,false);assert.equal($('notice-duration').value,'17');await click('[data-tab=security]');input('old-password','long test password');input('replacement-password','new strong password');await submit('password-form');assert.equal($('app').hidden,true);assert.equal($('replacement-password').value,'');
for(const call of mock.state.calls){assert.equal(call.path.startsWith("/api/cameras"),false);assert.equal(call.opts.headers?.Authorization,undefined);if(call.opts.credentials)assert.equal(call.opts.credentials,'same-origin');}
dom.window.close();console.log((native?'APP (canal nativo; fetch bloqueado): ':'PAINEL: ')+'PASS: cadastro, login sem segundo fator, login, restauração de sessão, CSRF nos comandos, limpeza de segredos, texto seguro, 21 ícones, 16 toques, temas, imagem, câmeras e VPN ocultas, YAML, perfil, revogação de celular, histórico e troca de senha.');}
main().catch(e=>{console.error(e);process.exitCode=1;if(window)window.close();});
